// Auto-generated by scripts/localize_project_images.py. Rerun after project-index.js refreshes.
window.projectGallery = {
  "2026-06-工作室项目-摩尔线程": [
    "./assets/project-assets/2026-06-工作室项目-摩尔线程/01.jpg",
    "./assets/project-assets/2026-06-工作室项目-摩尔线程/02.jpg",
    "./assets/project-assets/2026-06-工作室项目-摩尔线程/03.jpg",
    "./assets/project-assets/2026-06-工作室项目-摩尔线程/04.jpg",
    "./assets/project-assets/2026-06-工作室项目-摩尔线程/05.jpg",
    "./assets/project-assets/2026-06-工作室项目-摩尔线程/06.jpg"
  ],
  "2026-06-工作室项目-宁德时代": [
    "./assets/project-assets/2026-06-工作室项目-宁德时代/01.jpg",
    "./assets/project-assets/2026-06-工作室项目-宁德时代/02.jpg",
    "./assets/project-assets/2026-06-工作室项目-宁德时代/03.jpg",
    "./assets/project-assets/2026-06-工作室项目-宁德时代/04.jpg",
    "./assets/project-assets/2026-06-工作室项目-宁德时代/05.jpg"
  ],
  "2026-05-工作室项目-mpv之夜": [
    "./assets/project-assets/2026-05-工作室项目-mpv之夜/01.jpg",
    "./assets/project-assets/2026-05-工作室项目-mpv之夜/02.jpg",
    "./assets/project-assets/2026-05-工作室项目-mpv之夜/03.jpg",
    "./assets/project-assets/2026-05-工作室项目-mpv之夜/04.jpg",
    "./assets/project-assets/2026-05-工作室项目-mpv之夜/05.jpg",
    "./assets/project-assets/2026-05-工作室项目-mpv之夜/06.jpg"
  ],
  "2026-04-工作室项目-阳光电源": [
    "./assets/project-assets/2026-04-工作室项目-阳光电源/00.jpg",
    "./assets/project-assets/2026-04-工作室项目-阳光电源/01.jpg",
    "./assets/project-assets/2026-04-工作室项目-阳光电源/02.jpg",
    "./assets/project-assets/2026-04-工作室项目-阳光电源/03.jpg",
    "./assets/project-assets/2026-04-工作室项目-阳光电源/04.jpg",
    "./assets/project-assets/2026-04-工作室项目-阳光电源/05.jpg",
    "./assets/project-assets/2026-04-工作室项目-阳光电源/06.jpg",
    "./assets/project-assets/2026-04-工作室项目-阳光电源/07.jpg"
  ],
  "2026-04-工作室项目-中电展位方案": [
    "./assets/project-assets/2026-04-工作室项目-中电展位方案/01.jpg",
    "./assets/project-assets/2026-04-工作室项目-中电展位方案/02.jpg",
    "./assets/project-assets/2026-04-工作室项目-中电展位方案/03.jpg",
    "./assets/project-assets/2026-04-工作室项目-中电展位方案/04.jpg",
    "./assets/project-assets/2026-04-工作室项目-中电展位方案/05.jpg",
    "./assets/project-assets/2026-04-工作室项目-中电展位方案/06.jpg",
    "./assets/project-assets/2026-04-工作室项目-中电展位方案/07.jpg"
  ],
  "2026-04-工作室项目-rogbw": [
    "./assets/project-assets/2026-04-工作室项目-rogbw/01.jpg",
    "./assets/project-assets/2026-04-工作室项目-rogbw/02.jpg",
    "./assets/project-assets/2026-04-工作室项目-rogbw/03.jpg",
    "./assets/project-assets/2026-04-工作室项目-rogbw/04.jpg",
    "./assets/project-assets/2026-04-工作室项目-rogbw/05.jpg",
    "./assets/project-assets/2026-04-工作室项目-rogbw/06.jpg",
    "./assets/project-assets/2026-04-工作室项目-rogbw/07.jpg"
  ],
  "2026-04-工作室项目-tcl链博会": [
    "./assets/project-assets/2026-04-工作室项目-tcl链博会/01.jpg",
    "./assets/project-assets/2026-04-工作室项目-tcl链博会/02.jpg",
    "./assets/project-assets/2026-04-工作室项目-tcl链博会/03.jpg",
    "./assets/project-assets/2026-04-工作室项目-tcl链博会/04.jpg",
    "./assets/project-assets/2026-04-工作室项目-tcl链博会/05.jpg",
    "./assets/project-assets/2026-04-工作室项目-tcl链博会/06.jpg",
    "./assets/project-assets/2026-04-工作室项目-tcl链博会/07.jpg"
  ],
  "2026-04-工作室项目-trouver": [
    "./assets/project-assets/2026-04-工作室项目-trouver/01.jpg",
    "./assets/project-assets/2026-04-工作室项目-trouver/02.jpg",
    "./assets/project-assets/2026-04-工作室项目-trouver/03.jpg",
    "./assets/project-assets/2026-04-工作室项目-trouver/04.jpg",
    "./assets/project-assets/2026-04-工作室项目-trouver/05.jpg",
    "./assets/project-assets/2026-04-工作室项目-trouver/06.jpg",
    "./assets/project-assets/2026-04-工作室项目-trouver/07.jpg"
  ],
  "2026-03-工作室项目-隆基展台": [
    "./assets/project-assets/2026-03-工作室项目-隆基展台/01.jpg",
    "./assets/project-assets/2026-03-工作室项目-隆基展台/02.jpg"
  ],
  "2026-03-工作室项目-icara展运营": [
    "./assets/project-assets/2026-03-工作室项目-icara展运营/01.jpg",
    "./assets/project-assets/2026-03-工作室项目-icara展运营/02.jpg",
    "./assets/project-assets/2026-03-工作室项目-icara展运营/03.jpg",
    "./assets/project-assets/2026-03-工作室项目-icara展运营/04.jpg",
    "./assets/project-assets/2026-03-工作室项目-icara展运营/05.jpg",
    "./assets/project-assets/2026-03-工作室项目-icara展运营/06.jpg",
    "./assets/project-assets/2026-03-工作室项目-icara展运营/07.jpg"
  ],
  "2026-02-工作室项目-威麟汽车发布会": [
    "./assets/project-assets/2026-02-工作室项目-威麟汽车发布会/01.jpg",
    "./assets/project-assets/2026-02-工作室项目-威麟汽车发布会/02.jpg",
    "./assets/project-assets/2026-02-工作室项目-威麟汽车发布会/03.jpg",
    "./assets/project-assets/2026-02-工作室项目-威麟汽车发布会/04.jpg",
    "./assets/project-assets/2026-02-工作室项目-威麟汽车发布会/05.jpg",
    "./assets/project-assets/2026-02-工作室项目-威麟汽车发布会/06.jpg",
    "./assets/project-assets/2026-02-工作室项目-威麟汽车发布会/07.jpg"
  ],
  "2026-01-工作室项目-快手快手体育cny咱家的运动会": [
    "./assets/project-assets/2026-01-工作室项目-快手快手体育cny咱家的运动会/01.jpg",
    "./assets/project-assets/2026-01-工作室项目-快手快手体育cny咱家的运动会/02.jpg",
    "./assets/project-assets/2026-01-工作室项目-快手快手体育cny咱家的运动会/03.jpg",
    "./assets/project-assets/2026-01-工作室项目-快手快手体育cny咱家的运动会/04.jpg",
    "./assets/project-assets/2026-01-工作室项目-快手快手体育cny咱家的运动会/05.jpg",
    "./assets/project-assets/2026-01-工作室项目-快手快手体育cny咱家的运动会/06.jpg",
    "./assets/project-assets/2026-01-工作室项目-快手快手体育cny咱家的运动会/07.jpg"
  ],
  "2026-01-工作室项目-yonex嘉年华资料": [
    "./assets/project-assets/2026-01-工作室项目-yonex嘉年华资料/01.jpg",
    "./assets/project-assets/2026-01-工作室项目-yonex嘉年华资料/02.jpg",
    "./assets/project-assets/2026-01-工作室项目-yonex嘉年华资料/03.jpg",
    "./assets/project-assets/2026-01-工作室项目-yonex嘉年华资料/04.jpg",
    "./assets/project-assets/2026-01-工作室项目-yonex嘉年华资料/05.jpg",
    "./assets/project-assets/2026-01-工作室项目-yonex嘉年华资料/06.jpg",
    "./assets/project-assets/2026-01-工作室项目-yonex嘉年华资料/07.jpg"
  ],
  "2025-12-工作室项目-岚图技术品牌年度公关": [
    "./assets/project-assets/2025-12-工作室项目-岚图技术品牌年度公关/01.jpg",
    "./assets/project-assets/2025-12-工作室项目-岚图技术品牌年度公关/02.jpg",
    "./assets/project-assets/2025-12-工作室项目-岚图技术品牌年度公关/03.jpg",
    "./assets/project-assets/2025-12-工作室项目-岚图技术品牌年度公关/04.jpg",
    "./assets/project-assets/2025-12-工作室项目-岚图技术品牌年度公关/05.jpg",
    "./assets/project-assets/2025-12-工作室项目-岚图技术品牌年度公关/06.jpg",
    "./assets/project-assets/2025-12-工作室项目-岚图技术品牌年度公关/07.jpg"
  ],
  "2025-12-工作室项目-奇瑞技术品牌": [
    "./assets/project-assets/2025-12-工作室项目-奇瑞技术品牌/01.jpg",
    "./assets/project-assets/2025-12-工作室项目-奇瑞技术品牌/02.jpg",
    "./assets/project-assets/2025-12-工作室项目-奇瑞技术品牌/03.jpg",
    "./assets/project-assets/2025-12-工作室项目-奇瑞技术品牌/04.jpg",
    "./assets/project-assets/2025-12-工作室项目-奇瑞技术品牌/05.jpg",
    "./assets/project-assets/2025-12-工作室项目-奇瑞技术品牌/06.jpg"
  ],
  "2025-12-工作室项目-奇瑞泰国工厂": [
    "./assets/project-assets/2025-12-工作室项目-奇瑞泰国工厂/01.jpg",
    "./assets/project-assets/2025-12-工作室项目-奇瑞泰国工厂/02.jpg",
    "./assets/project-assets/2025-12-工作室项目-奇瑞泰国工厂/03.jpg",
    "./assets/project-assets/2025-12-工作室项目-奇瑞泰国工厂/04.jpg",
    "./assets/project-assets/2025-12-工作室项目-奇瑞泰国工厂/05.jpg",
    "./assets/project-assets/2025-12-工作室项目-奇瑞泰国工厂/06.jpg",
    "./assets/project-assets/2025-12-工作室项目-奇瑞泰国工厂/07.jpg"
  ],
  "2025-12-工作室项目-一汽丰田": [
    "./assets/project-assets/2025-12-工作室项目-一汽丰田/01.jpg",
    "./assets/project-assets/2025-12-工作室项目-一汽丰田/02.jpg",
    "./assets/project-assets/2025-12-工作室项目-一汽丰田/03.jpg",
    "./assets/project-assets/2025-12-工作室项目-一汽丰田/04.jpg",
    "./assets/project-assets/2025-12-工作室项目-一汽丰田/05.jpg",
    "./assets/project-assets/2025-12-工作室项目-一汽丰田/06.jpg",
    "./assets/project-assets/2025-12-工作室项目-一汽丰田/07.jpg"
  ],
  "2025-11-工作室项目-安道麦": [
    "./assets/project-assets/2025-11-工作室项目-安道麦/01.jpg",
    "./assets/project-assets/2025-11-工作室项目-安道麦/02.jpg",
    "./assets/project-assets/2025-11-工作室项目-安道麦/03.jpg",
    "./assets/project-assets/2025-11-工作室项目-安道麦/04.jpg",
    "./assets/project-assets/2025-11-工作室项目-安道麦/05.jpg",
    "./assets/project-assets/2025-11-工作室项目-安道麦/06.jpg",
    "./assets/project-assets/2025-11-工作室项目-安道麦/07.jpg"
  ],
  "2025-11-工作室项目-哈喽出行x网易云": [
    "./assets/project-assets/2025-11-工作室项目-哈喽出行x网易云/01.jpg",
    "./assets/project-assets/2025-11-工作室项目-哈喽出行x网易云/02.jpg",
    "./assets/project-assets/2025-11-工作室项目-哈喽出行x网易云/03.jpg",
    "./assets/project-assets/2025-11-工作室项目-哈喽出行x网易云/04.jpg",
    "./assets/project-assets/2025-11-工作室项目-哈喽出行x网易云/05.jpg",
    "./assets/project-assets/2025-11-工作室项目-哈喽出行x网易云/06.jpg",
    "./assets/project-assets/2025-11-工作室项目-哈喽出行x网易云/07.jpg"
  ],
  "2025-11-工作室项目-字节短剧行业": [
    "./assets/project-assets/2025-11-工作室项目-字节短剧行业/01.jpg",
    "./assets/project-assets/2025-11-工作室项目-字节短剧行业/02.jpg",
    "./assets/project-assets/2025-11-工作室项目-字节短剧行业/03.jpg",
    "./assets/project-assets/2025-11-工作室项目-字节短剧行业/04.jpg",
    "./assets/project-assets/2025-11-工作室项目-字节短剧行业/05.jpg",
    "./assets/project-assets/2025-11-工作室项目-字节短剧行业/06.jpg",
    "./assets/project-assets/2025-11-工作室项目-字节短剧行业/07.jpg"
  ],
  "2025-11-工作室项目-字节装修": [
    "./assets/project-assets/2025-11-工作室项目-字节装修/01.jpg",
    "./assets/project-assets/2025-11-工作室项目-字节装修/02.jpg",
    "./assets/project-assets/2025-11-工作室项目-字节装修/03.jpg",
    "./assets/project-assets/2025-11-工作室项目-字节装修/04.jpg",
    "./assets/project-assets/2025-11-工作室项目-字节装修/05.jpg",
    "./assets/project-assets/2025-11-工作室项目-字节装修/06.jpg",
    "./assets/project-assets/2025-11-工作室项目-字节装修/07.jpg"
  ],
  "2025-11-工作室项目-icar用户日": [
    "./assets/project-assets/2025-11-工作室项目-icar用户日/01.jpg",
    "./assets/project-assets/2025-11-工作室项目-icar用户日/02.jpg",
    "./assets/project-assets/2025-11-工作室项目-icar用户日/03.jpg",
    "./assets/project-assets/2025-11-工作室项目-icar用户日/04.jpg",
    "./assets/project-assets/2025-11-工作室项目-icar用户日/05.jpg",
    "./assets/project-assets/2025-11-工作室项目-icar用户日/06.jpg",
    "./assets/project-assets/2025-11-工作室项目-icar用户日/07.jpg"
  ],
  "2025-10-工作室项目-2025中国多智能体应用大会": [
    "./assets/project-assets/2025-10-工作室项目-2025中国多智能体应用大会/01.jpg",
    "./assets/project-assets/2025-10-工作室项目-2025中国多智能体应用大会/02.jpg",
    "./assets/project-assets/2025-10-工作室项目-2025中国多智能体应用大会/03.jpg",
    "./assets/project-assets/2025-10-工作室项目-2025中国多智能体应用大会/04.jpg",
    "./assets/project-assets/2025-10-工作室项目-2025中国多智能体应用大会/05.jpg",
    "./assets/project-assets/2025-10-工作室项目-2025中国多智能体应用大会/06.jpg",
    "./assets/project-assets/2025-10-工作室项目-2025中国多智能体应用大会/07.jpg"
  ],
  "2025-10-工作室项目-恒都律所年会2026": [
    "./assets/project-assets/2025-10-工作室项目-恒都律所年会2026/01.jpg",
    "./assets/project-assets/2025-10-工作室项目-恒都律所年会2026/02.jpg",
    "./assets/project-assets/2025-10-工作室项目-恒都律所年会2026/03.jpg",
    "./assets/project-assets/2025-10-工作室项目-恒都律所年会2026/04.jpg",
    "./assets/project-assets/2025-10-工作室项目-恒都律所年会2026/05.jpg",
    "./assets/project-assets/2025-10-工作室项目-恒都律所年会2026/06.jpg",
    "./assets/project-assets/2025-10-工作室项目-恒都律所年会2026/07.jpg"
  ],
  "2025-10-工作室项目-tata木门": [
    "./assets/project-assets/2025-10-工作室项目-tata木门/01.jpg",
    "./assets/project-assets/2025-10-工作室项目-tata木门/02.jpg",
    "./assets/project-assets/2025-10-工作室项目-tata木门/03.jpg",
    "./assets/project-assets/2025-10-工作室项目-tata木门/04.jpg",
    "./assets/project-assets/2025-10-工作室项目-tata木门/05.jpg",
    "./assets/project-assets/2025-10-工作室项目-tata木门/06.jpg",
    "./assets/project-assets/2025-10-工作室项目-tata木门/07.jpg"
  ],
  "2025-09-工作室项目-风云t9深度自驾公益体验之旅": [
    "./assets/project-assets/2025-09-工作室项目-风云t9深度自驾公益体验之旅/01.jpg",
    "./assets/project-assets/2025-09-工作室项目-风云t9深度自驾公益体验之旅/02.jpg",
    "./assets/project-assets/2025-09-工作室项目-风云t9深度自驾公益体验之旅/03.jpg",
    "./assets/project-assets/2025-09-工作室项目-风云t9深度自驾公益体验之旅/04.jpg",
    "./assets/project-assets/2025-09-工作室项目-风云t9深度自驾公益体验之旅/05.jpg",
    "./assets/project-assets/2025-09-工作室项目-风云t9深度自驾公益体验之旅/06.jpg",
    "./assets/project-assets/2025-09-工作室项目-风云t9深度自驾公益体验之旅/07.jpg"
  ],
  "2025-09-工作室项目-中国啤酒节南京站": [
    "./assets/project-assets/2025-09-工作室项目-中国啤酒节南京站/01.jpg",
    "./assets/project-assets/2025-09-工作室项目-中国啤酒节南京站/02.jpg",
    "./assets/project-assets/2025-09-工作室项目-中国啤酒节南京站/03.jpg",
    "./assets/project-assets/2025-09-工作室项目-中国啤酒节南京站/04.jpg",
    "./assets/project-assets/2025-09-工作室项目-中国啤酒节南京站/05.jpg",
    "./assets/project-assets/2025-09-工作室项目-中国啤酒节南京站/06.jpg",
    "./assets/project-assets/2025-09-工作室项目-中国啤酒节南京站/07.jpg"
  ],
  "2025-08-工作室项目-tmall": [
    "./assets/project-assets/2025-08-工作室项目-tmall/01.jpg",
    "./assets/project-assets/2025-08-工作室项目-tmall/02.jpg",
    "./assets/project-assets/2025-08-工作室项目-tmall/03.jpg",
    "./assets/project-assets/2025-08-工作室项目-tmall/04.jpg",
    "./assets/project-assets/2025-08-工作室项目-tmall/05.jpg",
    "./assets/project-assets/2025-08-工作室项目-tmall/06.jpg",
    "./assets/project-assets/2025-08-工作室项目-tmall/07.jpg"
  ],
  "2025-07-工作室项目-江淮": [
    "./assets/project-assets/2025-07-工作室项目-江淮/01.jpg",
    "./assets/project-assets/2025-07-工作室项目-江淮/02.jpg",
    "./assets/project-assets/2025-07-工作室项目-江淮/03.jpg",
    "./assets/project-assets/2025-07-工作室项目-江淮/04.jpg",
    "./assets/project-assets/2025-07-工作室项目-江淮/05.jpg",
    "./assets/project-assets/2025-07-工作室项目-江淮/06.jpg",
    "./assets/project-assets/2025-07-工作室项目-江淮/07.jpg"
  ],
  "2025-07-工作室项目-首钢方案": [
    "./assets/project-assets/2025-07-工作室项目-首钢方案/01.jpg",
    "./assets/project-assets/2025-07-工作室项目-首钢方案/02.jpg",
    "./assets/project-assets/2025-07-工作室项目-首钢方案/03.jpg",
    "./assets/project-assets/2025-07-工作室项目-首钢方案/04.jpg",
    "./assets/project-assets/2025-07-工作室项目-首钢方案/05.jpg",
    "./assets/project-assets/2025-07-工作室项目-首钢方案/06.jpg",
    "./assets/project-assets/2025-07-工作室项目-首钢方案/07.jpg"
  ],
  "2025-07-工作室项目-tt": [
    "./assets/project-assets/2025-07-工作室项目-tt/01.jpg",
    "./assets/project-assets/2025-07-工作室项目-tt/02.jpg",
    "./assets/project-assets/2025-07-工作室项目-tt/03.jpg",
    "./assets/project-assets/2025-07-工作室项目-tt/04.jpg",
    "./assets/project-assets/2025-07-工作室项目-tt/05.jpg",
    "./assets/project-assets/2025-07-工作室项目-tt/06.jpg",
    "./assets/project-assets/2025-07-工作室项目-tt/07.jpg"
  ],
  "2025-06-工作室项目-百度百度渠道合作伙伴大会": [
    "./assets/project-assets/2025-06-工作室项目-百度百度渠道合作伙伴大会/01.jpg",
    "./assets/project-assets/2025-06-工作室项目-百度百度渠道合作伙伴大会/02.jpg",
    "./assets/project-assets/2025-06-工作室项目-百度百度渠道合作伙伴大会/03.jpg",
    "./assets/project-assets/2025-06-工作室项目-百度百度渠道合作伙伴大会/04.jpg",
    "./assets/project-assets/2025-06-工作室项目-百度百度渠道合作伙伴大会/05.jpg",
    "./assets/project-assets/2025-06-工作室项目-百度百度渠道合作伙伴大会/06.jpg",
    "./assets/project-assets/2025-06-工作室项目-百度百度渠道合作伙伴大会/07.jpg"
  ],
  "2025-06-工作室项目-快手游音节": [
    "./assets/project-assets/2025-06-工作室项目-快手游音节/01.jpg",
    "./assets/project-assets/2025-06-工作室项目-快手游音节/02.jpg",
    "./assets/project-assets/2025-06-工作室项目-快手游音节/03.jpg",
    "./assets/project-assets/2025-06-工作室项目-快手游音节/04.jpg",
    "./assets/project-assets/2025-06-工作室项目-快手游音节/05.jpg",
    "./assets/project-assets/2025-06-工作室项目-快手游音节/06.jpg",
    "./assets/project-assets/2025-06-工作室项目-快手游音节/07.jpg"
  ],
  "2025-06-工作室项目-李尔30周年盛典": [
    "./assets/project-assets/2025-06-工作室项目-李尔30周年盛典/01.jpg",
    "./assets/project-assets/2025-06-工作室项目-李尔30周年盛典/02.jpg",
    "./assets/project-assets/2025-06-工作室项目-李尔30周年盛典/03.jpg",
    "./assets/project-assets/2025-06-工作室项目-李尔30周年盛典/04.jpg",
    "./assets/project-assets/2025-06-工作室项目-李尔30周年盛典/05.jpg",
    "./assets/project-assets/2025-06-工作室项目-李尔30周年盛典/06.jpg",
    "./assets/project-assets/2025-06-工作室项目-李尔30周年盛典/07.jpg"
  ],
  "2025-06-工作室项目-腾讯视频88动漫大赏": [
    "./assets/project-assets/2025-06-工作室项目-腾讯视频88动漫大赏/01.jpg",
    "./assets/project-assets/2025-06-工作室项目-腾讯视频88动漫大赏/02.jpg",
    "./assets/project-assets/2025-06-工作室项目-腾讯视频88动漫大赏/03.jpg",
    "./assets/project-assets/2025-06-工作室项目-腾讯视频88动漫大赏/04.jpg",
    "./assets/project-assets/2025-06-工作室项目-腾讯视频88动漫大赏/05.jpg",
    "./assets/project-assets/2025-06-工作室项目-腾讯视频88动漫大赏/06.jpg",
    "./assets/project-assets/2025-06-工作室项目-腾讯视频88动漫大赏/07.jpg"
  ],
  "2025-06-工作室项目-dnfcj": [
    "./assets/project-assets/2025-06-工作室项目-dnfcj/01.jpg",
    "./assets/project-assets/2025-06-工作室项目-dnfcj/02.jpg",
    "./assets/project-assets/2025-06-工作室项目-dnfcj/03.jpg",
    "./assets/project-assets/2025-06-工作室项目-dnfcj/04.jpg",
    "./assets/project-assets/2025-06-工作室项目-dnfcj/05.jpg",
    "./assets/project-assets/2025-06-工作室项目-dnfcj/06.jpg",
    "./assets/project-assets/2025-06-工作室项目-dnfcj/07.jpg"
  ],
  "2025-05-工作室项目-腾讯游戏cj": [
    "./assets/project-assets/2025-05-工作室项目-腾讯游戏cj/01.jpg",
    "./assets/project-assets/2025-05-工作室项目-腾讯游戏cj/02.jpg",
    "./assets/project-assets/2025-05-工作室项目-腾讯游戏cj/03.jpg",
    "./assets/project-assets/2025-05-工作室项目-腾讯游戏cj/04.jpg",
    "./assets/project-assets/2025-05-工作室项目-腾讯游戏cj/05.jpg",
    "./assets/project-assets/2025-05-工作室项目-腾讯游戏cj/06.jpg",
    "./assets/project-assets/2025-05-工作室项目-腾讯游戏cj/07.jpg"
  ],
  "2025-05-工作室项目-一汽丰田a展": [
    "./assets/project-assets/2025-05-工作室项目-一汽丰田a展/01.jpg",
    "./assets/project-assets/2025-05-工作室项目-一汽丰田a展/02.jpg",
    "./assets/project-assets/2025-05-工作室项目-一汽丰田a展/03.jpg",
    "./assets/project-assets/2025-05-工作室项目-一汽丰田a展/04.jpg",
    "./assets/project-assets/2025-05-工作室项目-一汽丰田a展/05.jpg",
    "./assets/project-assets/2025-05-工作室项目-一汽丰田a展/06.jpg",
    "./assets/project-assets/2025-05-工作室项目-一汽丰田a展/07.jpg"
  ],
  "2025-04-工作室项目-小米园区": [
    "./assets/project-assets/2025-04-工作室项目-小米园区/01.jpg",
    "./assets/project-assets/2025-04-工作室项目-小米园区/02.jpg",
    "./assets/project-assets/2025-04-工作室项目-小米园区/03.jpg",
    "./assets/project-assets/2025-04-工作室项目-小米园区/04.jpg",
    "./assets/project-assets/2025-04-工作室项目-小米园区/05.jpg",
    "./assets/project-assets/2025-04-工作室项目-小米园区/06.jpg",
    "./assets/project-assets/2025-04-工作室项目-小米园区/07.jpg"
  ],
  "2025-03-工作室项目-红旗出海项目": [
    "./assets/project-assets/2025-03-工作室项目-红旗出海项目/01.jpg",
    "./assets/project-assets/2025-03-工作室项目-红旗出海项目/02.jpg",
    "./assets/project-assets/2025-03-工作室项目-红旗出海项目/03.jpg",
    "./assets/project-assets/2025-03-工作室项目-红旗出海项目/04.jpg",
    "./assets/project-assets/2025-03-工作室项目-红旗出海项目/05.jpg",
    "./assets/project-assets/2025-03-工作室项目-红旗出海项目/06.jpg",
    "./assets/project-assets/2025-03-工作室项目-红旗出海项目/07.jpg"
  ],
  "2025-03-工作室项目-可灵ai": [
    "./assets/project-assets/2025-03-工作室项目-可灵ai/01.jpg",
    "./assets/project-assets/2025-03-工作室项目-可灵ai/02.jpg",
    "./assets/project-assets/2025-03-工作室项目-可灵ai/03.jpg",
    "./assets/project-assets/2025-03-工作室项目-可灵ai/04.jpg",
    "./assets/project-assets/2025-03-工作室项目-可灵ai/05.jpg",
    "./assets/project-assets/2025-03-工作室项目-可灵ai/06.jpg",
    "./assets/project-assets/2025-03-工作室项目-可灵ai/07.jpg"
  ],
  "2025-03-工作室项目-瑞思年会": [
    "./assets/project-assets/2025-03-工作室项目-瑞思年会/01.jpg",
    "./assets/project-assets/2025-03-工作室项目-瑞思年会/02.jpg",
    "./assets/project-assets/2025-03-工作室项目-瑞思年会/03.jpg",
    "./assets/project-assets/2025-03-工作室项目-瑞思年会/04.jpg",
    "./assets/project-assets/2025-03-工作室项目-瑞思年会/05.jpg",
    "./assets/project-assets/2025-03-工作室项目-瑞思年会/06.jpg",
    "./assets/project-assets/2025-03-工作室项目-瑞思年会/07.jpg"
  ],
  "2025-03-工作室项目-中和农信": [
    "./assets/project-assets/2025-03-工作室项目-中和农信/01.jpg",
    "./assets/project-assets/2025-03-工作室项目-中和农信/02.jpg",
    "./assets/project-assets/2025-03-工作室项目-中和农信/03.jpg",
    "./assets/project-assets/2025-03-工作室项目-中和农信/04.jpg",
    "./assets/project-assets/2025-03-工作室项目-中和农信/05.jpg",
    "./assets/project-assets/2025-03-工作室项目-中和农信/06.jpg",
    "./assets/project-assets/2025-03-工作室项目-中和农信/07.jpg"
  ],
  "2025-03-工作室项目-avatr": [
    "./assets/project-assets/2025-03-工作室项目-avatr/01.jpg",
    "./assets/project-assets/2025-03-工作室项目-avatr/02.jpg",
    "./assets/project-assets/2025-03-工作室项目-avatr/03.jpg",
    "./assets/project-assets/2025-03-工作室项目-avatr/04.jpg",
    "./assets/project-assets/2025-03-工作室项目-avatr/05.jpg",
    "./assets/project-assets/2025-03-工作室项目-avatr/06.jpg",
    "./assets/project-assets/2025-03-工作室项目-avatr/07.jpg"
  ],
  "2025-02-工作室项目-猿辅导智能硬件发布会": [
    "./assets/project-assets/2025-02-工作室项目-猿辅导智能硬件发布会/01.jpg",
    "./assets/project-assets/2025-02-工作室项目-猿辅导智能硬件发布会/02.jpg",
    "./assets/project-assets/2025-02-工作室项目-猿辅导智能硬件发布会/03.jpg",
    "./assets/project-assets/2025-02-工作室项目-猿辅导智能硬件发布会/04.jpg",
    "./assets/project-assets/2025-02-工作室项目-猿辅导智能硬件发布会/05.jpg",
    "./assets/project-assets/2025-02-工作室项目-猿辅导智能硬件发布会/06.jpg",
    "./assets/project-assets/2025-02-工作室项目-猿辅导智能硬件发布会/07.jpg"
  ],
  "2025-01-工作室项目-魏牌2025年活动运营项目技术任务方案": [
    "./assets/project-assets/2025-01-工作室项目-魏牌2025年活动运营项目技术任务方案/01.jpg",
    "./assets/project-assets/2025-01-工作室项目-魏牌2025年活动运营项目技术任务方案/02.jpg",
    "./assets/project-assets/2025-01-工作室项目-魏牌2025年活动运营项目技术任务方案/03.jpg",
    "./assets/project-assets/2025-01-工作室项目-魏牌2025年活动运营项目技术任务方案/04.jpg",
    "./assets/project-assets/2025-01-工作室项目-魏牌2025年活动运营项目技术任务方案/05.jpg",
    "./assets/project-assets/2025-01-工作室项目-魏牌2025年活动运营项目技术任务方案/06.jpg",
    "./assets/project-assets/2025-01-工作室项目-魏牌2025年活动运营项目技术任务方案/07.jpg"
  ],
  "2024-12-工作室项目-比亚迪智能化战略发布会": [
    "./assets/project-assets/2024-12-工作室项目-比亚迪智能化战略发布会/01.jpg",
    "./assets/project-assets/2024-12-工作室项目-比亚迪智能化战略发布会/02.jpg",
    "./assets/project-assets/2024-12-工作室项目-比亚迪智能化战略发布会/03.jpg",
    "./assets/project-assets/2024-12-工作室项目-比亚迪智能化战略发布会/04.jpg",
    "./assets/project-assets/2024-12-工作室项目-比亚迪智能化战略发布会/05.jpg",
    "./assets/project-assets/2024-12-工作室项目-比亚迪智能化战略发布会/06.jpg",
    "./assets/project-assets/2024-12-工作室项目-比亚迪智能化战略发布会/07.jpg"
  ],
  "2024-12-工作室项目-抖音直播嘉年华游园会": [
    "./assets/project-assets/2024-12-工作室项目-抖音直播嘉年华游园会/01.jpg",
    "./assets/project-assets/2024-12-工作室项目-抖音直播嘉年华游园会/02.jpg",
    "./assets/project-assets/2024-12-工作室项目-抖音直播嘉年华游园会/03.jpg",
    "./assets/project-assets/2024-12-工作室项目-抖音直播嘉年华游园会/04.jpg",
    "./assets/project-assets/2024-12-工作室项目-抖音直播嘉年华游园会/05.jpg",
    "./assets/project-assets/2024-12-工作室项目-抖音直播嘉年华游园会/06.jpg",
    "./assets/project-assets/2024-12-工作室项目-抖音直播嘉年华游园会/07.jpg"
  ],
  "2024-12-工作室项目-零跑a展": [
    "./assets/project-assets/2024-12-工作室项目-零跑a展/01.jpg",
    "./assets/project-assets/2024-12-工作室项目-零跑a展/02.jpg",
    "./assets/project-assets/2024-12-工作室项目-零跑a展/03.jpg",
    "./assets/project-assets/2024-12-工作室项目-零跑a展/04.jpg",
    "./assets/project-assets/2024-12-工作室项目-零跑a展/05.jpg",
    "./assets/project-assets/2024-12-工作室项目-零跑a展/06.jpg",
    "./assets/project-assets/2024-12-工作室项目-零跑a展/07.jpg"
  ],
  "2024-12-工作室项目-零碳园区新源未来协鑫能科万盛经开区零碳园区生态伙伴大会": [
    "./assets/project-assets/2024-12-工作室项目-零碳园区新源未来协鑫能科万盛经开区零碳园区生态伙伴大会/01.jpg",
    "./assets/project-assets/2024-12-工作室项目-零碳园区新源未来协鑫能科万盛经开区零碳园区生态伙伴大会/02.jpg",
    "./assets/project-assets/2024-12-工作室项目-零碳园区新源未来协鑫能科万盛经开区零碳园区生态伙伴大会/03.jpg",
    "./assets/project-assets/2024-12-工作室项目-零碳园区新源未来协鑫能科万盛经开区零碳园区生态伙伴大会/04.jpg",
    "./assets/project-assets/2024-12-工作室项目-零碳园区新源未来协鑫能科万盛经开区零碳园区生态伙伴大会/05.jpg",
    "./assets/project-assets/2024-12-工作室项目-零碳园区新源未来协鑫能科万盛经开区零碳园区生态伙伴大会/06.jpg",
    "./assets/project-assets/2024-12-工作室项目-零碳园区新源未来协鑫能科万盛经开区零碳园区生态伙伴大会/07.jpg"
  ],
  "2024-12-工作室项目-天神之眼第二轮": [
    "./assets/project-assets/2024-12-工作室项目-天神之眼第二轮/01.jpg",
    "./assets/project-assets/2024-12-工作室项目-天神之眼第二轮/02.jpg",
    "./assets/project-assets/2024-12-工作室项目-天神之眼第二轮/03.jpg",
    "./assets/project-assets/2024-12-工作室项目-天神之眼第二轮/04.jpg",
    "./assets/project-assets/2024-12-工作室项目-天神之眼第二轮/05.jpg",
    "./assets/project-assets/2024-12-工作室项目-天神之眼第二轮/06.jpg",
    "./assets/project-assets/2024-12-工作室项目-天神之眼第二轮/07.jpg"
  ],
  "2024-11-工作室项目-安道麦年会": [
    "./assets/project-assets/2024-11-工作室项目-安道麦年会/01.jpg",
    "./assets/project-assets/2024-11-工作室项目-安道麦年会/02.jpg",
    "./assets/project-assets/2024-11-工作室项目-安道麦年会/03.jpg",
    "./assets/project-assets/2024-11-工作室项目-安道麦年会/04.jpg",
    "./assets/project-assets/2024-11-工作室项目-安道麦年会/05.jpg",
    "./assets/project-assets/2024-11-工作室项目-安道麦年会/06.jpg",
    "./assets/project-assets/2024-11-工作室项目-安道麦年会/07.jpg"
  ],
  "2024-11-工作室项目-北京云2025年度规划": [
    "./assets/project-assets/2024-11-工作室项目-北京云2025年度规划/01.jpg",
    "./assets/project-assets/2024-11-工作室项目-北京云2025年度规划/02.jpg",
    "./assets/project-assets/2024-11-工作室项目-北京云2025年度规划/03.jpg",
    "./assets/project-assets/2024-11-工作室项目-北京云2025年度规划/04.jpg",
    "./assets/project-assets/2024-11-工作室项目-北京云2025年度规划/05.jpg",
    "./assets/project-assets/2024-11-工作室项目-北京云2025年度规划/06.jpg",
    "./assets/project-assets/2024-11-工作室项目-北京云2025年度规划/07.jpg"
  ],
  "2024-11-工作室项目-冰buff杯": [
    "./assets/project-assets/2024-11-工作室项目-冰buff杯/01.jpg",
    "./assets/project-assets/2024-11-工作室项目-冰buff杯/02.jpg",
    "./assets/project-assets/2024-11-工作室项目-冰buff杯/03.jpg",
    "./assets/project-assets/2024-11-工作室项目-冰buff杯/04.jpg",
    "./assets/project-assets/2024-11-工作室项目-冰buff杯/05.jpg",
    "./assets/project-assets/2024-11-工作室项目-冰buff杯/06.jpg",
    "./assets/project-assets/2024-11-工作室项目-冰buff杯/07.jpg"
  ],
  "2024-11-工作室项目-恒都律所年会": [
    "./assets/project-assets/2024-11-工作室项目-恒都律所年会/01.jpg",
    "./assets/project-assets/2024-11-工作室项目-恒都律所年会/02.jpg",
    "./assets/project-assets/2024-11-工作室项目-恒都律所年会/03.jpg",
    "./assets/project-assets/2024-11-工作室项目-恒都律所年会/04.jpg",
    "./assets/project-assets/2024-11-工作室项目-恒都律所年会/05.jpg",
    "./assets/project-assets/2024-11-工作室项目-恒都律所年会/06.jpg",
    "./assets/project-assets/2024-11-工作室项目-恒都律所年会/07.jpg"
  ],
  "2024-11-工作室项目-腾讯碳普惠峰会": [
    "./assets/project-assets/2024-11-工作室项目-腾讯碳普惠峰会/01.jpg",
    "./assets/project-assets/2024-11-工作室项目-腾讯碳普惠峰会/02.jpg",
    "./assets/project-assets/2024-11-工作室项目-腾讯碳普惠峰会/03.jpg",
    "./assets/project-assets/2024-11-工作室项目-腾讯碳普惠峰会/04.jpg",
    "./assets/project-assets/2024-11-工作室项目-腾讯碳普惠峰会/05.jpg",
    "./assets/project-assets/2024-11-工作室项目-腾讯碳普惠峰会/06.jpg",
    "./assets/project-assets/2024-11-工作室项目-腾讯碳普惠峰会/07.jpg"
  ],
  "2024-11-工作室项目-星火学院年会": [
    "./assets/project-assets/2024-11-工作室项目-星火学院年会/01.jpg",
    "./assets/project-assets/2024-11-工作室项目-星火学院年会/02.jpg",
    "./assets/project-assets/2024-11-工作室项目-星火学院年会/03.jpg",
    "./assets/project-assets/2024-11-工作室项目-星火学院年会/04.jpg",
    "./assets/project-assets/2024-11-工作室项目-星火学院年会/05.jpg",
    "./assets/project-assets/2024-11-工作室项目-星火学院年会/06.jpg",
    "./assets/project-assets/2024-11-工作室项目-星火学院年会/07.jpg"
  ],
  "2024-11-工作室项目-icar品牌年度": [
    "./assets/project-assets/2024-11-工作室项目-icar品牌年度/01.jpg",
    "./assets/project-assets/2024-11-工作室项目-icar品牌年度/02.jpg",
    "./assets/project-assets/2024-11-工作室项目-icar品牌年度/03.jpg",
    "./assets/project-assets/2024-11-工作室项目-icar品牌年度/04.jpg",
    "./assets/project-assets/2024-11-工作室项目-icar品牌年度/05.jpg",
    "./assets/project-assets/2024-11-工作室项目-icar品牌年度/06.jpg",
    "./assets/project-assets/2024-11-工作室项目-icar品牌年度/07.jpg"
  ],
  "2024-10-工作室项目-埃安泰国车展": [
    "./assets/project-assets/2024-10-工作室项目-埃安泰国车展/01.jpg",
    "./assets/project-assets/2024-10-工作室项目-埃安泰国车展/02.jpg",
    "./assets/project-assets/2024-10-工作室项目-埃安泰国车展/03.jpg",
    "./assets/project-assets/2024-10-工作室项目-埃安泰国车展/04.jpg",
    "./assets/project-assets/2024-10-工作室项目-埃安泰国车展/05.jpg",
    "./assets/project-assets/2024-10-工作室项目-埃安泰国车展/06.jpg",
    "./assets/project-assets/2024-10-工作室项目-埃安泰国车展/07.jpg"
  ],
  "2024-10-工作室项目-抖音冰雪温泉季": [
    "./assets/project-assets/2024-10-工作室项目-抖音冰雪温泉季/01.jpg",
    "./assets/project-assets/2024-10-工作室项目-抖音冰雪温泉季/02.jpg",
    "./assets/project-assets/2024-10-工作室项目-抖音冰雪温泉季/03.jpg",
    "./assets/project-assets/2024-10-工作室项目-抖音冰雪温泉季/04.jpg",
    "./assets/project-assets/2024-10-工作室项目-抖音冰雪温泉季/05.jpg",
    "./assets/project-assets/2024-10-工作室项目-抖音冰雪温泉季/06.jpg",
    "./assets/project-assets/2024-10-工作室项目-抖音冰雪温泉季/07.jpg"
  ],
  "2024-10-工作室项目-长安十二时辰街区互动": [
    "./assets/project-assets/2024-10-工作室项目-长安十二时辰街区互动/01.jpg",
    "./assets/project-assets/2024-10-工作室项目-长安十二时辰街区互动/02.jpg",
    "./assets/project-assets/2024-10-工作室项目-长安十二时辰街区互动/03.jpg",
    "./assets/project-assets/2024-10-工作室项目-长安十二时辰街区互动/04.jpg",
    "./assets/project-assets/2024-10-工作室项目-长安十二时辰街区互动/05.jpg",
    "./assets/project-assets/2024-10-工作室项目-长安十二时辰街区互动/06.jpg",
    "./assets/project-assets/2024-10-工作室项目-长安十二时辰街区互动/07.jpg"
  ],
  "2024-10-工作室项目-比亚迪a展运营": [
    "./assets/project-assets/2024-10-工作室项目-比亚迪a展运营/01.jpg",
    "./assets/project-assets/2024-10-工作室项目-比亚迪a展运营/02.jpg",
    "./assets/project-assets/2024-10-工作室项目-比亚迪a展运营/03.jpg",
    "./assets/project-assets/2024-10-工作室项目-比亚迪a展运营/04.jpg",
    "./assets/project-assets/2024-10-工作室项目-比亚迪a展运营/05.jpg",
    "./assets/project-assets/2024-10-工作室项目-比亚迪a展运营/06.jpg",
    "./assets/project-assets/2024-10-工作室项目-比亚迪a展运营/07.jpg"
  ],
  "2024-09-工作室项目-百信银行": [
    "./assets/project-assets/2024-09-工作室项目-百信银行/01.jpg",
    "./assets/project-assets/2024-09-工作室项目-百信银行/02.jpg",
    "./assets/project-assets/2024-09-工作室项目-百信银行/03.jpg",
    "./assets/project-assets/2024-09-工作室项目-百信银行/04.jpg",
    "./assets/project-assets/2024-09-工作室项目-百信银行/05.jpg",
    "./assets/project-assets/2024-09-工作室项目-百信银行/06.jpg",
    "./assets/project-assets/2024-09-工作室项目-百信银行/07.jpg"
  ],
  "2024-09-工作室项目-捷途汽车全球旅行大会": [
    "./assets/project-assets/2024-09-工作室项目-捷途汽车全球旅行大会/01.jpg",
    "./assets/project-assets/2024-09-工作室项目-捷途汽车全球旅行大会/02.jpg",
    "./assets/project-assets/2024-09-工作室项目-捷途汽车全球旅行大会/03.jpg",
    "./assets/project-assets/2024-09-工作室项目-捷途汽车全球旅行大会/04.jpg",
    "./assets/project-assets/2024-09-工作室项目-捷途汽车全球旅行大会/05.jpg",
    "./assets/project-assets/2024-09-工作室项目-捷途汽车全球旅行大会/06.jpg",
    "./assets/project-assets/2024-09-工作室项目-捷途汽车全球旅行大会/07.jpg"
  ],
  "2024-09-工作室项目-一汽奔腾": [
    "./assets/project-assets/2024-09-工作室项目-一汽奔腾/01.jpg",
    "./assets/project-assets/2024-09-工作室项目-一汽奔腾/02.jpg",
    "./assets/project-assets/2024-09-工作室项目-一汽奔腾/03.jpg",
    "./assets/project-assets/2024-09-工作室项目-一汽奔腾/04.jpg",
    "./assets/project-assets/2024-09-工作室项目-一汽奔腾/05.jpg",
    "./assets/project-assets/2024-09-工作室项目-一汽奔腾/06.jpg",
    "./assets/project-assets/2024-09-工作室项目-一汽奔腾/07.jpg"
  ],
  "2024-09-工作室项目-比亚迪宋pro": [
    "./assets/project-assets/2024-09-工作室项目-比亚迪宋pro/01.jpg",
    "./assets/project-assets/2024-09-工作室项目-比亚迪宋pro/02.jpg",
    "./assets/project-assets/2024-09-工作室项目-比亚迪宋pro/03.jpg",
    "./assets/project-assets/2024-09-工作室项目-比亚迪宋pro/04.jpg",
    "./assets/project-assets/2024-09-工作室项目-比亚迪宋pro/05.jpg",
    "./assets/project-assets/2024-09-工作室项目-比亚迪宋pro/06.jpg",
    "./assets/project-assets/2024-09-工作室项目-比亚迪宋pro/07.jpg"
  ],
  "2024-08-工作室项目-华为hns": [
    "./assets/project-assets/2024-08-工作室项目-华为hns/01.jpg",
    "./assets/project-assets/2024-08-工作室项目-华为hns/02.jpg",
    "./assets/project-assets/2024-08-工作室项目-华为hns/03.jpg",
    "./assets/project-assets/2024-08-工作室项目-华为hns/04.jpg",
    "./assets/project-assets/2024-08-工作室项目-华为hns/05.jpg",
    "./assets/project-assets/2024-08-工作室项目-华为hns/06.jpg",
    "./assets/project-assets/2024-08-工作室项目-华为hns/07.jpg"
  ],
  "2024-08-工作室项目-奇瑞生态大会": [
    "./assets/project-assets/2024-08-工作室项目-奇瑞生态大会/01.jpg",
    "./assets/project-assets/2024-08-工作室项目-奇瑞生态大会/02.jpg",
    "./assets/project-assets/2024-08-工作室项目-奇瑞生态大会/03.jpg",
    "./assets/project-assets/2024-08-工作室项目-奇瑞生态大会/04.jpg",
    "./assets/project-assets/2024-08-工作室项目-奇瑞生态大会/05.jpg",
    "./assets/project-assets/2024-08-工作室项目-奇瑞生态大会/06.jpg",
    "./assets/project-assets/2024-08-工作室项目-奇瑞生态大会/07.jpg"
  ],
  "2024-08-工作室项目-腾讯openday": [
    "./assets/project-assets/2024-08-工作室项目-腾讯openday/01.jpg",
    "./assets/project-assets/2024-08-工作室项目-腾讯openday/02.jpg",
    "./assets/project-assets/2024-08-工作室项目-腾讯openday/03.jpg",
    "./assets/project-assets/2024-08-工作室项目-腾讯openday/04.jpg",
    "./assets/project-assets/2024-08-工作室项目-腾讯openday/05.jpg",
    "./assets/project-assets/2024-08-工作室项目-腾讯openday/06.jpg",
    "./assets/project-assets/2024-08-工作室项目-腾讯openday/07.jpg"
  ],
  "2024-08-工作室项目-gcpolymerscustomerforumproposal": [
    "./assets/project-assets/2024-08-工作室项目-gcpolymerscustomerforumproposal/01.jpg",
    "./assets/project-assets/2024-08-工作室项目-gcpolymerscustomerforumproposal/02.jpg",
    "./assets/project-assets/2024-08-工作室项目-gcpolymerscustomerforumproposal/03.jpg",
    "./assets/project-assets/2024-08-工作室项目-gcpolymerscustomerforumproposal/04.jpg",
    "./assets/project-assets/2024-08-工作室项目-gcpolymerscustomerforumproposal/05.jpg",
    "./assets/project-assets/2024-08-工作室项目-gcpolymerscustomerforumproposal/06.jpg",
    "./assets/project-assets/2024-08-工作室项目-gcpolymerscustomerforumproposal/07.jpg"
  ],
  "2024-07-工作室项目-奥迪67月": [
    "./assets/project-assets/2024-07-工作室项目-奥迪67月/01.jpg",
    "./assets/project-assets/2024-07-工作室项目-奥迪67月/02.jpg",
    "./assets/project-assets/2024-07-工作室项目-奥迪67月/03.jpg",
    "./assets/project-assets/2024-07-工作室项目-奥迪67月/04.jpg",
    "./assets/project-assets/2024-07-工作室项目-奥迪67月/05.jpg",
    "./assets/project-assets/2024-07-工作室项目-奥迪67月/06.jpg",
    "./assets/project-assets/2024-07-工作室项目-奥迪67月/07.jpg"
  ],
  "2024-07-工作室项目-百信银行": [
    "./assets/project-assets/2024-07-工作室项目-百信银行/01.jpg",
    "./assets/project-assets/2024-07-工作室项目-百信银行/02.jpg",
    "./assets/project-assets/2024-07-工作室项目-百信银行/03.jpg",
    "./assets/project-assets/2024-07-工作室项目-百信银行/04.jpg",
    "./assets/project-assets/2024-07-工作室项目-百信银行/05.jpg",
    "./assets/project-assets/2024-07-工作室项目-百信银行/06.jpg",
    "./assets/project-assets/2024-07-工作室项目-百信银行/07.jpg"
  ],
  "2024-07-工作室项目-大悦城活动": [
    "./assets/project-assets/2024-07-工作室项目-大悦城活动/01.jpg",
    "./assets/project-assets/2024-07-工作室项目-大悦城活动/02.jpg",
    "./assets/project-assets/2024-07-工作室项目-大悦城活动/03.jpg",
    "./assets/project-assets/2024-07-工作室项目-大悦城活动/04.jpg",
    "./assets/project-assets/2024-07-工作室项目-大悦城活动/05.jpg",
    "./assets/project-assets/2024-07-工作室项目-大悦城活动/06.jpg",
    "./assets/project-assets/2024-07-工作室项目-大悦城活动/07.jpg"
  ],
  "2024-07-工作室项目-联想联通合作伙伴大会展台": [
    "./assets/project-assets/2024-07-工作室项目-联想联通合作伙伴大会展台/01.jpg",
    "./assets/project-assets/2024-07-工作室项目-联想联通合作伙伴大会展台/02.jpg",
    "./assets/project-assets/2024-07-工作室项目-联想联通合作伙伴大会展台/03.jpg",
    "./assets/project-assets/2024-07-工作室项目-联想联通合作伙伴大会展台/04.jpg",
    "./assets/project-assets/2024-07-工作室项目-联想联通合作伙伴大会展台/05.jpg",
    "./assets/project-assets/2024-07-工作室项目-联想联通合作伙伴大会展台/06.jpg",
    "./assets/project-assets/2024-07-工作室项目-联想联通合作伙伴大会展台/07.jpg"
  ],
  "2024-07-工作室项目-小鹏发布会": [
    "./assets/project-assets/2024-07-工作室项目-小鹏发布会/01.jpg",
    "./assets/project-assets/2024-07-工作室项目-小鹏发布会/02.jpg",
    "./assets/project-assets/2024-07-工作室项目-小鹏发布会/03.jpg",
    "./assets/project-assets/2024-07-工作室项目-小鹏发布会/04.jpg",
    "./assets/project-assets/2024-07-工作室项目-小鹏发布会/05.jpg",
    "./assets/project-assets/2024-07-工作室项目-小鹏发布会/06.jpg",
    "./assets/project-assets/2024-07-工作室项目-小鹏发布会/07.jpg"
  ],
  "2024-07-工作室项目-一丰放价活动": [
    "./assets/project-assets/2024-07-工作室项目-一丰放价活动/01.jpg",
    "./assets/project-assets/2024-07-工作室项目-一丰放价活动/02.jpg",
    "./assets/project-assets/2024-07-工作室项目-一丰放价活动/03.jpg",
    "./assets/project-assets/2024-07-工作室项目-一丰放价活动/04.jpg",
    "./assets/project-assets/2024-07-工作室项目-一丰放价活动/05.jpg",
    "./assets/project-assets/2024-07-工作室项目-一丰放价活动/06.jpg",
    "./assets/project-assets/2024-07-工作室项目-一丰放价活动/07.jpg"
  ],
  "2024-06-工作室项目-奇瑞十一营销": [
    "./assets/project-assets/2024-06-工作室项目-奇瑞十一营销/01.jpg",
    "./assets/project-assets/2024-06-工作室项目-奇瑞十一营销/02.jpg",
    "./assets/project-assets/2024-06-工作室项目-奇瑞十一营销/03.jpg",
    "./assets/project-assets/2024-06-工作室项目-奇瑞十一营销/04.jpg",
    "./assets/project-assets/2024-06-工作室项目-奇瑞十一营销/05.jpg",
    "./assets/project-assets/2024-06-工作室项目-奇瑞十一营销/06.jpg",
    "./assets/project-assets/2024-06-工作室项目-奇瑞十一营销/07.jpg"
  ],
  "2024-06-工作室项目-一汽大众发现之旅20": [
    "./assets/project-assets/2024-06-工作室项目-一汽大众发现之旅20/01.jpg",
    "./assets/project-assets/2024-06-工作室项目-一汽大众发现之旅20/02.jpg",
    "./assets/project-assets/2024-06-工作室项目-一汽大众发现之旅20/03.jpg",
    "./assets/project-assets/2024-06-工作室项目-一汽大众发现之旅20/04.jpg",
    "./assets/project-assets/2024-06-工作室项目-一汽大众发现之旅20/05.jpg",
    "./assets/project-assets/2024-06-工作室项目-一汽大众发现之旅20/06.jpg",
    "./assets/project-assets/2024-06-工作室项目-一汽大众发现之旅20/07.jpg"
  ],
  "2024-06-工作室项目-长江学院": [
    "./assets/project-assets/2024-06-工作室项目-长江学院/01.jpg",
    "./assets/project-assets/2024-06-工作室项目-长江学院/02.jpg",
    "./assets/project-assets/2024-06-工作室项目-长江学院/03.jpg",
    "./assets/project-assets/2024-06-工作室项目-长江学院/04.jpg",
    "./assets/project-assets/2024-06-工作室项目-长江学院/05.jpg",
    "./assets/project-assets/2024-06-工作室项目-长江学院/06.jpg",
    "./assets/project-assets/2024-06-工作室项目-长江学院/07.jpg"
  ],
  "2024-05-工作室项目-零跑汽车发布会": [
    "./assets/project-assets/2024-05-工作室项目-零跑汽车发布会/01.jpg",
    "./assets/project-assets/2024-05-工作室项目-零跑汽车发布会/02.jpg",
    "./assets/project-assets/2024-05-工作室项目-零跑汽车发布会/03.jpg",
    "./assets/project-assets/2024-05-工作室项目-零跑汽车发布会/04.jpg",
    "./assets/project-assets/2024-05-工作室项目-零跑汽车发布会/05.jpg",
    "./assets/project-assets/2024-05-工作室项目-零跑汽车发布会/06.jpg",
    "./assets/project-assets/2024-05-工作室项目-零跑汽车发布会/07.jpg"
  ],
  "2024-05-工作室项目-aif打击黑产": [
    "./assets/project-assets/2024-05-工作室项目-aif打击黑产/01.jpg",
    "./assets/project-assets/2024-05-工作室项目-aif打击黑产/02.jpg",
    "./assets/project-assets/2024-05-工作室项目-aif打击黑产/03.jpg",
    "./assets/project-assets/2024-05-工作室项目-aif打击黑产/04.jpg",
    "./assets/project-assets/2024-05-工作室项目-aif打击黑产/05.jpg",
    "./assets/project-assets/2024-05-工作室项目-aif打击黑产/06.jpg",
    "./assets/project-assets/2024-05-工作室项目-aif打击黑产/07.jpg"
  ],
  "2024-05-工作室项目-wavesummit": [
    "./assets/project-assets/2024-05-工作室项目-wavesummit/01.jpg",
    "./assets/project-assets/2024-05-工作室项目-wavesummit/02.jpg",
    "./assets/project-assets/2024-05-工作室项目-wavesummit/03.jpg",
    "./assets/project-assets/2024-05-工作室项目-wavesummit/04.jpg",
    "./assets/project-assets/2024-05-工作室项目-wavesummit/05.jpg",
    "./assets/project-assets/2024-05-工作室项目-wavesummit/06.jpg",
    "./assets/project-assets/2024-05-工作室项目-wavesummit/07.jpg"
  ],
  "2024-04-工作室项目-抖音星球": [
    "./assets/project-assets/2024-04-工作室项目-抖音星球/01.jpg",
    "./assets/project-assets/2024-04-工作室项目-抖音星球/02.jpg",
    "./assets/project-assets/2024-04-工作室项目-抖音星球/03.jpg",
    "./assets/project-assets/2024-04-工作室项目-抖音星球/04.jpg"
  ],
  "2024-04-工作室项目-消防安全大赛": [
    "./assets/project-assets/2024-04-工作室项目-消防安全大赛/01.jpg",
    "./assets/project-assets/2024-04-工作室项目-消防安全大赛/02.jpg",
    "./assets/project-assets/2024-04-工作室项目-消防安全大赛/03.jpg",
    "./assets/project-assets/2024-04-工作室项目-消防安全大赛/04.jpg",
    "./assets/project-assets/2024-04-工作室项目-消防安全大赛/05.jpg",
    "./assets/project-assets/2024-04-工作室项目-消防安全大赛/06.jpg",
    "./assets/project-assets/2024-04-工作室项目-消防安全大赛/07.jpg"
  ],
  "2024-04-工作室项目-自贡健走跑": [
    "./assets/project-assets/2024-04-工作室项目-自贡健走跑/01.jpg",
    "./assets/project-assets/2024-04-工作室项目-自贡健走跑/02.jpg",
    "./assets/project-assets/2024-04-工作室项目-自贡健走跑/03.jpg",
    "./assets/project-assets/2024-04-工作室项目-自贡健走跑/04.jpg",
    "./assets/project-assets/2024-04-工作室项目-自贡健走跑/05.jpg",
    "./assets/project-assets/2024-04-工作室项目-自贡健走跑/06.jpg",
    "./assets/project-assets/2024-04-工作室项目-自贡健走跑/07.jpg"
  ],
  "2024-03-工作室项目-拜耳": [
    "./assets/project-assets/2024-03-工作室项目-拜耳/01.jpg",
    "./assets/project-assets/2024-03-工作室项目-拜耳/02.jpg",
    "./assets/project-assets/2024-03-工作室项目-拜耳/03.jpg",
    "./assets/project-assets/2024-03-工作室项目-拜耳/04.jpg",
    "./assets/project-assets/2024-03-工作室项目-拜耳/05.jpg",
    "./assets/project-assets/2024-03-工作室项目-拜耳/06.jpg",
    "./assets/project-assets/2024-03-工作室项目-拜耳/07.jpg"
  ],
  "2024-03-工作室项目-奇瑞a展运营": [
    "./assets/project-assets/2024-03-工作室项目-奇瑞a展运营/01.jpg",
    "./assets/project-assets/2024-03-工作室项目-奇瑞a展运营/02.jpg",
    "./assets/project-assets/2024-03-工作室项目-奇瑞a展运营/03.jpg",
    "./assets/project-assets/2024-03-工作室项目-奇瑞a展运营/04.jpg",
    "./assets/project-assets/2024-03-工作室项目-奇瑞a展运营/05.jpg",
    "./assets/project-assets/2024-03-工作室项目-奇瑞a展运营/06.jpg",
    "./assets/project-assets/2024-03-工作室项目-奇瑞a展运营/07.jpg"
  ],
  "2024-03-工作室项目-fusionsolarnight2024": [
    "./assets/project-assets/2024-03-工作室项目-fusionsolarnight2024/01.jpg",
    "./assets/project-assets/2024-03-工作室项目-fusionsolarnight2024/02.jpg",
    "./assets/project-assets/2024-03-工作室项目-fusionsolarnight2024/03.jpg",
    "./assets/project-assets/2024-03-工作室项目-fusionsolarnight2024/04.jpg",
    "./assets/project-assets/2024-03-工作室项目-fusionsolarnight2024/05.jpg",
    "./assets/project-assets/2024-03-工作室项目-fusionsolarnight2024/06.jpg"
  ],
  "2024-02-工作室项目-坦客联盟": [
    "./assets/project-assets/2024-02-工作室项目-坦客联盟/01.jpg",
    "./assets/project-assets/2024-02-工作室项目-坦客联盟/02.jpg",
    "./assets/project-assets/2024-02-工作室项目-坦客联盟/03.jpg",
    "./assets/project-assets/2024-02-工作室项目-坦客联盟/04.jpg",
    "./assets/project-assets/2024-02-工作室项目-坦客联盟/05.jpg",
    "./assets/project-assets/2024-02-工作室项目-坦客联盟/06.jpg",
    "./assets/project-assets/2024-02-工作室项目-坦客联盟/07.jpg"
  ],
  "2024-02-工作室项目-中国国际金融展联想联想开天联合展位": [
    "./assets/project-assets/2024-02-工作室项目-中国国际金融展联想联想开天联合展位/01.jpg",
    "./assets/project-assets/2024-02-工作室项目-中国国际金融展联想联想开天联合展位/02.jpg",
    "./assets/project-assets/2024-02-工作室项目-中国国际金融展联想联想开天联合展位/03.jpg",
    "./assets/project-assets/2024-02-工作室项目-中国国际金融展联想联想开天联合展位/04.jpg",
    "./assets/project-assets/2024-02-工作室项目-中国国际金融展联想联想开天联合展位/05.jpg",
    "./assets/project-assets/2024-02-工作室项目-中国国际金融展联想联想开天联合展位/06.jpg",
    "./assets/project-assets/2024-02-工作室项目-中国国际金融展联想联想开天联合展位/07.jpg"
  ],
  "2024-01-工作室项目-快手理想家": [
    "./assets/project-assets/2024-01-工作室项目-快手理想家/01.jpg",
    "./assets/project-assets/2024-01-工作室项目-快手理想家/02.jpg",
    "./assets/project-assets/2024-01-工作室项目-快手理想家/03.jpg",
    "./assets/project-assets/2024-01-工作室项目-快手理想家/04.jpg",
    "./assets/project-assets/2024-01-工作室项目-快手理想家/05.jpg",
    "./assets/project-assets/2024-01-工作室项目-快手理想家/06.jpg",
    "./assets/project-assets/2024-01-工作室项目-快手理想家/07.jpg"
  ],
  "2024-01-工作室项目-锐捷共建大会": [
    "./assets/project-assets/2024-01-工作室项目-锐捷共建大会/01.jpg",
    "./assets/project-assets/2024-01-工作室项目-锐捷共建大会/02.jpg",
    "./assets/project-assets/2024-01-工作室项目-锐捷共建大会/03.jpg",
    "./assets/project-assets/2024-01-工作室项目-锐捷共建大会/04.jpg",
    "./assets/project-assets/2024-01-工作室项目-锐捷共建大会/05.jpg",
    "./assets/project-assets/2024-01-工作室项目-锐捷共建大会/06.jpg",
    "./assets/project-assets/2024-01-工作室项目-锐捷共建大会/07.jpg"
  ],
  "2023-11-工作室项目-吉祥航空年会": [
    "./assets/project-assets/2023-11-工作室项目-吉祥航空年会/01.jpg",
    "./assets/project-assets/2023-11-工作室项目-吉祥航空年会/02.jpg",
    "./assets/project-assets/2023-11-工作室项目-吉祥航空年会/03.jpg",
    "./assets/project-assets/2023-11-工作室项目-吉祥航空年会/04.jpg",
    "./assets/project-assets/2023-11-工作室项目-吉祥航空年会/05.jpg",
    "./assets/project-assets/2023-11-工作室项目-吉祥航空年会/06.jpg",
    "./assets/project-assets/2023-11-工作室项目-吉祥航空年会/07.jpg"
  ],
  "2023-11-工作室项目-茅台保健酒": [
    "./assets/project-assets/2023-11-工作室项目-茅台保健酒/01.jpg",
    "./assets/project-assets/2023-11-工作室项目-茅台保健酒/02.jpg",
    "./assets/project-assets/2023-11-工作室项目-茅台保健酒/03.jpg",
    "./assets/project-assets/2023-11-工作室项目-茅台保健酒/04.jpg",
    "./assets/project-assets/2023-11-工作室项目-茅台保健酒/05.jpg",
    "./assets/project-assets/2023-11-工作室项目-茅台保健酒/06.jpg",
    "./assets/project-assets/2023-11-工作室项目-茅台保健酒/07.jpg"
  ],
  "2023-11-工作室项目-星途年会": [
    "./assets/project-assets/2023-11-工作室项目-星途年会/01.jpg",
    "./assets/project-assets/2023-11-工作室项目-星途年会/02.jpg",
    "./assets/project-assets/2023-11-工作室项目-星途年会/03.jpg",
    "./assets/project-assets/2023-11-工作室项目-星途年会/04.jpg",
    "./assets/project-assets/2023-11-工作室项目-星途年会/05.jpg",
    "./assets/project-assets/2023-11-工作室项目-星途年会/06.jpg",
    "./assets/project-assets/2023-11-工作室项目-星途年会/07.jpg"
  ],
  "2023-10-工作室项目-埃安泰国车展": [
    "./assets/project-assets/2023-10-工作室项目-埃安泰国车展/01.jpg",
    "./assets/project-assets/2023-10-工作室项目-埃安泰国车展/02.jpg",
    "./assets/project-assets/2023-10-工作室项目-埃安泰国车展/03.jpg",
    "./assets/project-assets/2023-10-工作室项目-埃安泰国车展/04.jpg",
    "./assets/project-assets/2023-10-工作室项目-埃安泰国车展/05.jpg",
    "./assets/project-assets/2023-10-工作室项目-埃安泰国车展/06.jpg",
    "./assets/project-assets/2023-10-工作室项目-埃安泰国车展/07.jpg"
  ],
  "2023-10-工作室项目-储能峰会": [
    "./assets/project-assets/2023-10-工作室项目-储能峰会/01.jpg",
    "./assets/project-assets/2023-10-工作室项目-储能峰会/02.jpg",
    "./assets/project-assets/2023-10-工作室项目-储能峰会/03.jpg",
    "./assets/project-assets/2023-10-工作室项目-储能峰会/04.jpg",
    "./assets/project-assets/2023-10-工作室项目-储能峰会/05.jpg",
    "./assets/project-assets/2023-10-工作室项目-储能峰会/06.jpg",
    "./assets/project-assets/2023-10-工作室项目-储能峰会/07.jpg"
  ],
  "2023-10-工作室项目-快手汽车年度商业推介会": [
    "./assets/project-assets/2023-10-工作室项目-快手汽车年度商业推介会/01.jpg",
    "./assets/project-assets/2023-10-工作室项目-快手汽车年度商业推介会/02.jpg",
    "./assets/project-assets/2023-10-工作室项目-快手汽车年度商业推介会/03.jpg",
    "./assets/project-assets/2023-10-工作室项目-快手汽车年度商业推介会/04.jpg",
    "./assets/project-assets/2023-10-工作室项目-快手汽车年度商业推介会/05.jpg",
    "./assets/project-assets/2023-10-工作室项目-快手汽车年度商业推介会/06.jpg",
    "./assets/project-assets/2023-10-工作室项目-快手汽车年度商业推介会/07.jpg"
  ],
  "2023-10-工作室项目-美团企业版用户大会": [
    "./assets/project-assets/2023-10-工作室项目-美团企业版用户大会/01.jpg",
    "./assets/project-assets/2023-10-工作室项目-美团企业版用户大会/02.jpg",
    "./assets/project-assets/2023-10-工作室项目-美团企业版用户大会/03.jpg",
    "./assets/project-assets/2023-10-工作室项目-美团企业版用户大会/04.jpg",
    "./assets/project-assets/2023-10-工作室项目-美团企业版用户大会/05.jpg",
    "./assets/project-assets/2023-10-工作室项目-美团企业版用户大会/06.jpg",
    "./assets/project-assets/2023-10-工作室项目-美团企业版用户大会/07.jpg"
  ],
  "2023-10-工作室项目-星途品鉴会": [
    "./assets/project-assets/2023-10-工作室项目-星途品鉴会/01.jpg",
    "./assets/project-assets/2023-10-工作室项目-星途品鉴会/02.jpg",
    "./assets/project-assets/2023-10-工作室项目-星途品鉴会/03.jpg",
    "./assets/project-assets/2023-10-工作室项目-星途品鉴会/04.jpg",
    "./assets/project-assets/2023-10-工作室项目-星途品鉴会/05.jpg",
    "./assets/project-assets/2023-10-工作室项目-星途品鉴会/06.jpg",
    "./assets/project-assets/2023-10-工作室项目-星途品鉴会/07.jpg"
  ],
  "2023-09-工作室项目-抖音心动玩乐节": [
    "./assets/project-assets/2023-09-工作室项目-抖音心动玩乐节/01.jpg",
    "./assets/project-assets/2023-09-工作室项目-抖音心动玩乐节/02.jpg",
    "./assets/project-assets/2023-09-工作室项目-抖音心动玩乐节/03.jpg",
    "./assets/project-assets/2023-09-工作室项目-抖音心动玩乐节/04.jpg",
    "./assets/project-assets/2023-09-工作室项目-抖音心动玩乐节/05.jpg",
    "./assets/project-assets/2023-09-工作室项目-抖音心动玩乐节/06.jpg"
  ],
  "2023-09-工作室项目-抖音珠宝行业峰会": [
    "./assets/project-assets/2023-09-工作室项目-抖音珠宝行业峰会/01.jpg",
    "./assets/project-assets/2023-09-工作室项目-抖音珠宝行业峰会/02.jpg",
    "./assets/project-assets/2023-09-工作室项目-抖音珠宝行业峰会/03.jpg",
    "./assets/project-assets/2023-09-工作室项目-抖音珠宝行业峰会/04.jpg"
  ],
  "2023-09-工作室项目-广汽传祺广州车展": [
    "./assets/project-assets/2023-09-工作室项目-广汽传祺广州车展/01.jpg",
    "./assets/project-assets/2023-09-工作室项目-广汽传祺广州车展/02.jpg",
    "./assets/project-assets/2023-09-工作室项目-广汽传祺广州车展/03.jpg",
    "./assets/project-assets/2023-09-工作室项目-广汽传祺广州车展/04.jpg",
    "./assets/project-assets/2023-09-工作室项目-广汽传祺广州车展/05.jpg",
    "./assets/project-assets/2023-09-工作室项目-广汽传祺广州车展/06.jpg",
    "./assets/project-assets/2023-09-工作室项目-广汽传祺广州车展/07.jpg"
  ],
  "2023-09-工作室项目-京东供应链金融科技大会": [
    "./assets/project-assets/2023-09-工作室项目-京东供应链金融科技大会/01.jpg",
    "./assets/project-assets/2023-09-工作室项目-京东供应链金融科技大会/02.jpg",
    "./assets/project-assets/2023-09-工作室项目-京东供应链金融科技大会/03.jpg",
    "./assets/project-assets/2023-09-工作室项目-京东供应链金融科技大会/04.jpg",
    "./assets/project-assets/2023-09-工作室项目-京东供应链金融科技大会/05.jpg",
    "./assets/project-assets/2023-09-工作室项目-京东供应链金融科技大会/06.jpg",
    "./assets/project-assets/2023-09-工作室项目-京东供应链金融科技大会/07.jpg"
  ],
  "2023-09-工作室项目-小米互联网合作伙伴大会": [
    "./assets/project-assets/2023-09-工作室项目-小米互联网合作伙伴大会/01.jpg",
    "./assets/project-assets/2023-09-工作室项目-小米互联网合作伙伴大会/02.jpg",
    "./assets/project-assets/2023-09-工作室项目-小米互联网合作伙伴大会/03.jpg",
    "./assets/project-assets/2023-09-工作室项目-小米互联网合作伙伴大会/04.jpg",
    "./assets/project-assets/2023-09-工作室项目-小米互联网合作伙伴大会/05.jpg",
    "./assets/project-assets/2023-09-工作室项目-小米互联网合作伙伴大会/06.jpg",
    "./assets/project-assets/2023-09-工作室项目-小米互联网合作伙伴大会/07.jpg"
  ],
  "2023-08-工作室项目-京东工业降本增效": [
    "./assets/project-assets/2023-08-工作室项目-京东工业降本增效/01.jpg",
    "./assets/project-assets/2023-08-工作室项目-京东工业降本增效/02.jpg",
    "./assets/project-assets/2023-08-工作室项目-京东工业降本增效/03.jpg",
    "./assets/project-assets/2023-08-工作室项目-京东工业降本增效/04.jpg",
    "./assets/project-assets/2023-08-工作室项目-京东工业降本增效/05.jpg",
    "./assets/project-assets/2023-08-工作室项目-京东工业降本增效/06.jpg",
    "./assets/project-assets/2023-08-工作室项目-京东工业降本增效/07.jpg"
  ],
  "2023-08-工作室项目-美团春归": [
    "./assets/project-assets/2023-08-工作室项目-美团春归/01.jpg",
    "./assets/project-assets/2023-08-工作室项目-美团春归/02.jpg",
    "./assets/project-assets/2023-08-工作室项目-美团春归/03.jpg",
    "./assets/project-assets/2023-08-工作室项目-美团春归/04.jpg",
    "./assets/project-assets/2023-08-工作室项目-美团春归/05.jpg",
    "./assets/project-assets/2023-08-工作室项目-美团春归/06.jpg",
    "./assets/project-assets/2023-08-工作室项目-美团春归/07.jpg"
  ],
  "2023-08-工作室项目-小米运营商展位": [
    "./assets/project-assets/2023-08-工作室项目-小米运营商展位/01.jpg",
    "./assets/project-assets/2023-08-工作室项目-小米运营商展位/02.jpg",
    "./assets/project-assets/2023-08-工作室项目-小米运营商展位/03.jpg",
    "./assets/project-assets/2023-08-工作室项目-小米运营商展位/04.jpg",
    "./assets/project-assets/2023-08-工作室项目-小米运营商展位/05.jpg",
    "./assets/project-assets/2023-08-工作室项目-小米运营商展位/06.jpg",
    "./assets/project-assets/2023-08-工作室项目-小米运营商展位/07.jpg"
  ],
  "2023-08-工作室项目-coffeebreak修改": [
    "./assets/project-assets/2023-08-工作室项目-coffeebreak修改/01.jpg",
    "./assets/project-assets/2023-08-工作室项目-coffeebreak修改/02.jpg",
    "./assets/project-assets/2023-08-工作室项目-coffeebreak修改/03.jpg",
    "./assets/project-assets/2023-08-工作室项目-coffeebreak修改/04.jpg",
    "./assets/project-assets/2023-08-工作室项目-coffeebreak修改/05.jpg",
    "./assets/project-assets/2023-08-工作室项目-coffeebreak修改/06.jpg",
    "./assets/project-assets/2023-08-工作室项目-coffeebreak修改/07.jpg"
  ],
  "2023-07-工作室项目-爱奇艺年框": [
    "./assets/project-assets/2023-07-工作室项目-爱奇艺年框/01.jpg",
    "./assets/project-assets/2023-07-工作室项目-爱奇艺年框/02.jpg",
    "./assets/project-assets/2023-07-工作室项目-爱奇艺年框/03.jpg",
    "./assets/project-assets/2023-07-工作室项目-爱奇艺年框/04.jpg",
    "./assets/project-assets/2023-07-工作室项目-爱奇艺年框/05.jpg",
    "./assets/project-assets/2023-07-工作室项目-爱奇艺年框/06.jpg",
    "./assets/project-assets/2023-07-工作室项目-爱奇艺年框/07.jpg"
  ],
  "2023-07-工作室项目-丛台酒": [
    "./assets/project-assets/2023-07-工作室项目-丛台酒/01.jpg",
    "./assets/project-assets/2023-07-工作室项目-丛台酒/02.jpg",
    "./assets/project-assets/2023-07-工作室项目-丛台酒/03.jpg",
    "./assets/project-assets/2023-07-工作室项目-丛台酒/04.jpg",
    "./assets/project-assets/2023-07-工作室项目-丛台酒/05.jpg",
    "./assets/project-assets/2023-07-工作室项目-丛台酒/06.jpg",
    "./assets/project-assets/2023-07-工作室项目-丛台酒/07.jpg"
  ],
  "2023-07-工作室项目-美的年框": [
    "./assets/project-assets/2023-07-工作室项目-美的年框/01.jpg",
    "./assets/project-assets/2023-07-工作室项目-美的年框/02.jpg",
    "./assets/project-assets/2023-07-工作室项目-美的年框/03.jpg",
    "./assets/project-assets/2023-07-工作室项目-美的年框/04.jpg",
    "./assets/project-assets/2023-07-工作室项目-美的年框/05.jpg",
    "./assets/project-assets/2023-07-工作室项目-美的年框/06.jpg",
    "./assets/project-assets/2023-07-工作室项目-美的年框/07.jpg"
  ],
  "2023-07-工作室项目-头号大师": [
    "./assets/project-assets/2023-07-工作室项目-头号大师/01.jpg",
    "./assets/project-assets/2023-07-工作室项目-头号大师/02.jpg",
    "./assets/project-assets/2023-07-工作室项目-头号大师/03.jpg",
    "./assets/project-assets/2023-07-工作室项目-头号大师/04.jpg",
    "./assets/project-assets/2023-07-工作室项目-头号大师/05.jpg",
    "./assets/project-assets/2023-07-工作室项目-头号大师/06.jpg",
    "./assets/project-assets/2023-07-工作室项目-头号大师/07.jpg"
  ],
  "2023-06-工作室项目-航天信息新品发布会": [
    "./assets/project-assets/2023-06-工作室项目-航天信息新品发布会/01.jpg",
    "./assets/project-assets/2023-06-工作室项目-航天信息新品发布会/02.jpg",
    "./assets/project-assets/2023-06-工作室项目-航天信息新品发布会/03.jpg",
    "./assets/project-assets/2023-06-工作室项目-航天信息新品发布会/04.jpg",
    "./assets/project-assets/2023-06-工作室项目-航天信息新品发布会/05.jpg",
    "./assets/project-assets/2023-06-工作室项目-航天信息新品发布会/06.jpg",
    "./assets/project-assets/2023-06-工作室项目-航天信息新品发布会/07.jpg"
  ],
  "2023-06-工作室项目-美的年框": [
    "./assets/project-assets/2023-06-工作室项目-美的年框/01.jpg",
    "./assets/project-assets/2023-06-工作室项目-美的年框/02.jpg",
    "./assets/project-assets/2023-06-工作室项目-美的年框/03.jpg",
    "./assets/project-assets/2023-06-工作室项目-美的年框/04.jpg",
    "./assets/project-assets/2023-06-工作室项目-美的年框/05.jpg",
    "./assets/project-assets/2023-06-工作室项目-美的年框/06.jpg",
    "./assets/project-assets/2023-06-工作室项目-美的年框/07.jpg"
  ],
  "2023-06-工作室项目-小米cj": [
    "./assets/project-assets/2023-06-工作室项目-小米cj/01.jpg",
    "./assets/project-assets/2023-06-工作室项目-小米cj/02.jpg",
    "./assets/project-assets/2023-06-工作室项目-小米cj/03.jpg",
    "./assets/project-assets/2023-06-工作室项目-小米cj/04.jpg",
    "./assets/project-assets/2023-06-工作室项目-小米cj/05.jpg",
    "./assets/project-assets/2023-06-工作室项目-小米cj/06.jpg",
    "./assets/project-assets/2023-06-工作室项目-小米cj/07.jpg"
  ],
  "2023-06-工作室项目-coffeeebreak": [
    "./assets/project-assets/2023-06-工作室项目-coffeeebreak/01.jpg",
    "./assets/project-assets/2023-06-工作室项目-coffeeebreak/02.jpg",
    "./assets/project-assets/2023-06-工作室项目-coffeeebreak/03.jpg",
    "./assets/project-assets/2023-06-工作室项目-coffeeebreak/04.jpg",
    "./assets/project-assets/2023-06-工作室项目-coffeeebreak/05.jpg",
    "./assets/project-assets/2023-06-工作室项目-coffeeebreak/06.jpg",
    "./assets/project-assets/2023-06-工作室项目-coffeeebreak/07.jpg"
  ],
  "2023-05-工作室项目-丛台酒": [
    "./assets/project-assets/2023-05-工作室项目-丛台酒/01.jpg",
    "./assets/project-assets/2023-05-工作室项目-丛台酒/02.jpg",
    "./assets/project-assets/2023-05-工作室项目-丛台酒/03.jpg",
    "./assets/project-assets/2023-05-工作室项目-丛台酒/04.jpg",
    "./assets/project-assets/2023-05-工作室项目-丛台酒/05.jpg",
    "./assets/project-assets/2023-05-工作室项目-丛台酒/06.jpg",
    "./assets/project-assets/2023-05-工作室项目-丛台酒/07.jpg"
  ],
  "2023-05-工作室项目-火山引擎": [
    "./assets/project-assets/2023-05-工作室项目-火山引擎/01.jpg",
    "./assets/project-assets/2023-05-工作室项目-火山引擎/02.jpg",
    "./assets/project-assets/2023-05-工作室项目-火山引擎/03.jpg",
    "./assets/project-assets/2023-05-工作室项目-火山引擎/04.jpg",
    "./assets/project-assets/2023-05-工作室项目-火山引擎/05.jpg",
    "./assets/project-assets/2023-05-工作室项目-火山引擎/06.jpg",
    "./assets/project-assets/2023-05-工作室项目-火山引擎/07.jpg"
  ],
  "2023-05-工作室项目-六桂福长城走秀": [
    "./assets/project-assets/2023-05-工作室项目-六桂福长城走秀/01.jpg",
    "./assets/project-assets/2023-05-工作室项目-六桂福长城走秀/02.jpg",
    "./assets/project-assets/2023-05-工作室项目-六桂福长城走秀/03.jpg",
    "./assets/project-assets/2023-05-工作室项目-六桂福长城走秀/04.jpg",
    "./assets/project-assets/2023-05-工作室项目-六桂福长城走秀/05.jpg",
    "./assets/project-assets/2023-05-工作室项目-六桂福长城走秀/06.jpg",
    "./assets/project-assets/2023-05-工作室项目-六桂福长城走秀/07.jpg"
  ],
  "2023-04-工作室项目-联想凌拓": [
    "./assets/project-assets/2023-04-工作室项目-联想凌拓/01.jpg",
    "./assets/project-assets/2023-04-工作室项目-联想凌拓/02.jpg",
    "./assets/project-assets/2023-04-工作室项目-联想凌拓/03.jpg",
    "./assets/project-assets/2023-04-工作室项目-联想凌拓/04.jpg",
    "./assets/project-assets/2023-04-工作室项目-联想凌拓/05.jpg",
    "./assets/project-assets/2023-04-工作室项目-联想凌拓/06.jpg",
    "./assets/project-assets/2023-04-工作室项目-联想凌拓/07.jpg"
  ],
  "2023-04-工作室项目-colmo": [
    "./assets/project-assets/2023-04-工作室项目-colmo/01.jpg",
    "./assets/project-assets/2023-04-工作室项目-colmo/02.jpg",
    "./assets/project-assets/2023-04-工作室项目-colmo/03.jpg",
    "./assets/project-assets/2023-04-工作室项目-colmo/04.jpg",
    "./assets/project-assets/2023-04-工作室项目-colmo/05.jpg",
    "./assets/project-assets/2023-04-工作室项目-colmo/06.jpg",
    "./assets/project-assets/2023-04-工作室项目-colmo/07.jpg"
  ],
  "2023-04-工作室项目-oureafterhours": [
    "./assets/project-assets/2023-04-工作室项目-oureafterhours/01.jpg",
    "./assets/project-assets/2023-04-工作室项目-oureafterhours/02.jpg",
    "./assets/project-assets/2023-04-工作室项目-oureafterhours/03.jpg",
    "./assets/project-assets/2023-04-工作室项目-oureafterhours/04.jpg",
    "./assets/project-assets/2023-04-工作室项目-oureafterhours/05.jpg",
    "./assets/project-assets/2023-04-工作室项目-oureafterhours/06.jpg",
    "./assets/project-assets/2023-04-工作室项目-oureafterhours/07.jpg"
  ],
  "2023-04-工作室项目-rogbw": [
    "./assets/project-assets/2023-04-工作室项目-rogbw/01.jpg",
    "./assets/project-assets/2023-04-工作室项目-rogbw/02.jpg",
    "./assets/project-assets/2023-04-工作室项目-rogbw/03.jpg",
    "./assets/project-assets/2023-04-工作室项目-rogbw/04.jpg",
    "./assets/project-assets/2023-04-工作室项目-rogbw/05.jpg",
    "./assets/project-assets/2023-04-工作室项目-rogbw/06.jpg",
    "./assets/project-assets/2023-04-工作室项目-rogbw/07.jpg"
  ],
  "2023-03-工作室项目-北京现代国际展": [
    "./assets/project-assets/2023-03-工作室项目-北京现代国际展/01.jpg",
    "./assets/project-assets/2023-03-工作室项目-北京现代国际展/02.jpg",
    "./assets/project-assets/2023-03-工作室项目-北京现代国际展/03.jpg",
    "./assets/project-assets/2023-03-工作室项目-北京现代国际展/04.jpg",
    "./assets/project-assets/2023-03-工作室项目-北京现代国际展/05.jpg",
    "./assets/project-assets/2023-03-工作室项目-北京现代国际展/06.jpg",
    "./assets/project-assets/2023-03-工作室项目-北京现代国际展/07.jpg"
  ],
  "2023-03-工作室项目-传祺20231": [
    "./assets/project-assets/2023-03-工作室项目-传祺20231/01.jpg",
    "./assets/project-assets/2023-03-工作室项目-传祺20231/02.jpg",
    "./assets/project-assets/2023-03-工作室项目-传祺20231/03.jpg",
    "./assets/project-assets/2023-03-工作室项目-传祺20231/04.jpg",
    "./assets/project-assets/2023-03-工作室项目-传祺20231/05.jpg",
    "./assets/project-assets/2023-03-工作室项目-传祺20231/06.jpg",
    "./assets/project-assets/2023-03-工作室项目-传祺20231/07.jpg"
  ],
  "2023-03-工作室项目-极氪飞盘大赛": [
    "./assets/project-assets/2023-03-工作室项目-极氪飞盘大赛/01.jpg",
    "./assets/project-assets/2023-03-工作室项目-极氪飞盘大赛/02.jpg",
    "./assets/project-assets/2023-03-工作室项目-极氪飞盘大赛/03.jpg",
    "./assets/project-assets/2023-03-工作室项目-极氪飞盘大赛/04.jpg",
    "./assets/project-assets/2023-03-工作室项目-极氪飞盘大赛/05.jpg",
    "./assets/project-assets/2023-03-工作室项目-极氪飞盘大赛/06.jpg",
    "./assets/project-assets/2023-03-工作室项目-极氪飞盘大赛/07.jpg"
  ],
  "2023-03-工作室项目-岚图": [
    "./assets/project-assets/2023-03-工作室项目-岚图/01.jpg",
    "./assets/project-assets/2023-03-工作室项目-岚图/02.jpg",
    "./assets/project-assets/2023-03-工作室项目-岚图/03.jpg",
    "./assets/project-assets/2023-03-工作室项目-岚图/04.jpg",
    "./assets/project-assets/2023-03-工作室项目-岚图/05.jpg",
    "./assets/project-assets/2023-03-工作室项目-岚图/06.jpg",
    "./assets/project-assets/2023-03-工作室项目-岚图/07.jpg"
  ],
  "2023-03-工作室项目-麻辣麻辣新品上市促销": [
    "./assets/project-assets/2023-03-工作室项目-麻辣麻辣新品上市促销/01.jpg",
    "./assets/project-assets/2023-03-工作室项目-麻辣麻辣新品上市促销/02.jpg",
    "./assets/project-assets/2023-03-工作室项目-麻辣麻辣新品上市促销/03.jpg",
    "./assets/project-assets/2023-03-工作室项目-麻辣麻辣新品上市促销/04.jpg",
    "./assets/project-assets/2023-03-工作室项目-麻辣麻辣新品上市促销/05.jpg",
    "./assets/project-assets/2023-03-工作室项目-麻辣麻辣新品上市促销/06.jpg",
    "./assets/project-assets/2023-03-工作室项目-麻辣麻辣新品上市促销/07.jpg"
  ],
  "2023-03-工作室项目-长图": [
    "./assets/project-assets/2023-03-工作室项目-长图/01.jpg",
    "./assets/project-assets/2023-03-工作室项目-长图/02.jpg",
    "./assets/project-assets/2023-03-工作室项目-长图/03.jpg",
    "./assets/project-assets/2023-03-工作室项目-长图/04.jpg",
    "./assets/project-assets/2023-03-工作室项目-长图/05.jpg",
    "./assets/project-assets/2023-03-工作室项目-长图/06.jpg",
    "./assets/project-assets/2023-03-工作室项目-长图/07.jpg"
  ],
  "2023-02-工作室项目-抖音电商大会": [
    "./assets/project-assets/2023-02-工作室项目-抖音电商大会/01.jpg",
    "./assets/project-assets/2023-02-工作室项目-抖音电商大会/02.jpg",
    "./assets/project-assets/2023-02-工作室项目-抖音电商大会/03.jpg",
    "./assets/project-assets/2023-02-工作室项目-抖音电商大会/04.jpg",
    "./assets/project-assets/2023-02-工作室项目-抖音电商大会/05.jpg",
    "./assets/project-assets/2023-02-工作室项目-抖音电商大会/06.jpg",
    "./assets/project-assets/2023-02-工作室项目-抖音电商大会/07.jpg"
  ],
  "2023-02-工作室项目-卫龙第三轮": [
    "./assets/project-assets/2023-02-工作室项目-卫龙第三轮/01.jpg",
    "./assets/project-assets/2023-02-工作室项目-卫龙第三轮/02.jpg",
    "./assets/project-assets/2023-02-工作室项目-卫龙第三轮/03.jpg",
    "./assets/project-assets/2023-02-工作室项目-卫龙第三轮/04.jpg",
    "./assets/project-assets/2023-02-工作室项目-卫龙第三轮/05.jpg",
    "./assets/project-assets/2023-02-工作室项目-卫龙第三轮/06.jpg",
    "./assets/project-assets/2023-02-工作室项目-卫龙第三轮/07.jpg"
  ],
  "2023-02-工作室项目-易点云年会": [
    "./assets/project-assets/2023-02-工作室项目-易点云年会/01.jpg",
    "./assets/project-assets/2023-02-工作室项目-易点云年会/02.jpg",
    "./assets/project-assets/2023-02-工作室项目-易点云年会/03.jpg",
    "./assets/project-assets/2023-02-工作室项目-易点云年会/04.jpg",
    "./assets/project-assets/2023-02-工作室项目-易点云年会/05.jpg",
    "./assets/project-assets/2023-02-工作室项目-易点云年会/06.jpg",
    "./assets/project-assets/2023-02-工作室项目-易点云年会/07.jpg"
  ],
  "2023-02-工作室项目-比亚迪第二轮": [
    "./assets/project-assets/2023-02-工作室项目-比亚迪第二轮/01.jpg",
    "./assets/project-assets/2023-02-工作室项目-比亚迪第二轮/02.jpg",
    "./assets/project-assets/2023-02-工作室项目-比亚迪第二轮/03.jpg",
    "./assets/project-assets/2023-02-工作室项目-比亚迪第二轮/04.jpg",
    "./assets/project-assets/2023-02-工作室项目-比亚迪第二轮/05.jpg",
    "./assets/project-assets/2023-02-工作室项目-比亚迪第二轮/06.jpg",
    "./assets/project-assets/2023-02-工作室项目-比亚迪第二轮/07.jpg"
  ],
  "2023-01-工作室项目-比亚迪bc第一轮": [
    "./assets/project-assets/2023-01-工作室项目-比亚迪bc第一轮/01.jpg",
    "./assets/project-assets/2023-01-工作室项目-比亚迪bc第一轮/02.jpg",
    "./assets/project-assets/2023-01-工作室项目-比亚迪bc第一轮/03.jpg",
    "./assets/project-assets/2023-01-工作室项目-比亚迪bc第一轮/04.jpg",
    "./assets/project-assets/2023-01-工作室项目-比亚迪bc第一轮/05.jpg",
    "./assets/project-assets/2023-01-工作室项目-比亚迪bc第一轮/06.jpg",
    "./assets/project-assets/2023-01-工作室项目-比亚迪bc第一轮/07.jpg"
  ],
  "2023-01-工作室项目-怀疆集团": [
    "./assets/project-assets/2023-01-工作室项目-怀疆集团/01.jpg",
    "./assets/project-assets/2023-01-工作室项目-怀疆集团/02.jpg",
    "./assets/project-assets/2023-01-工作室项目-怀疆集团/03.jpg",
    "./assets/project-assets/2023-01-工作室项目-怀疆集团/04.jpg",
    "./assets/project-assets/2023-01-工作室项目-怀疆集团/05.jpg",
    "./assets/project-assets/2023-01-工作室项目-怀疆集团/06.jpg",
    "./assets/project-assets/2023-01-工作室项目-怀疆集团/07.jpg"
  ],
  "2023-01-工作室项目-卫龙第二轮": [
    "./assets/project-assets/2023-01-工作室项目-卫龙第二轮/01.jpg",
    "./assets/project-assets/2023-01-工作室项目-卫龙第二轮/02.jpg",
    "./assets/project-assets/2023-01-工作室项目-卫龙第二轮/03.jpg",
    "./assets/project-assets/2023-01-工作室项目-卫龙第二轮/04.jpg",
    "./assets/project-assets/2023-01-工作室项目-卫龙第二轮/05.jpg",
    "./assets/project-assets/2023-01-工作室项目-卫龙第二轮/06.jpg",
    "./assets/project-assets/2023-01-工作室项目-卫龙第二轮/07.jpg"
  ],
  "2023-00-工作室项目-同事同期案例": [
    "./assets/project-assets/2023-00-工作室项目-同事同期案例/01.jpg",
    "./assets/project-assets/2023-00-工作室项目-同事同期案例/02.jpg",
    "./assets/project-assets/2023-00-工作室项目-同事同期案例/03.jpg",
    "./assets/project-assets/2023-00-工作室项目-同事同期案例/04.jpg",
    "./assets/project-assets/2023-00-工作室项目-同事同期案例/05.jpg",
    "./assets/project-assets/2023-00-工作室项目-同事同期案例/06.jpg",
    "./assets/project-assets/2023-00-工作室项目-同事同期案例/07.jpg"
  ],
  "2022-12-工作室项目-卫龙辣条第一轮": [
    "./assets/project-assets/2022-12-工作室项目-卫龙辣条第一轮/01.jpg",
    "./assets/project-assets/2022-12-工作室项目-卫龙辣条第一轮/02.jpg",
    "./assets/project-assets/2022-12-工作室项目-卫龙辣条第一轮/03.jpg",
    "./assets/project-assets/2022-12-工作室项目-卫龙辣条第一轮/04.jpg",
    "./assets/project-assets/2022-12-工作室项目-卫龙辣条第一轮/05.jpg",
    "./assets/project-assets/2022-12-工作室项目-卫龙辣条第一轮/06.jpg",
    "./assets/project-assets/2022-12-工作室项目-卫龙辣条第一轮/07.jpg"
  ],
  "2022-11-工作室项目-李宁成都太古里开业": [
    "./assets/project-assets/2022-11-工作室项目-李宁成都太古里开业/01.jpg",
    "./assets/project-assets/2022-11-工作室项目-李宁成都太古里开业/02.jpg",
    "./assets/project-assets/2022-11-工作室项目-李宁成都太古里开业/03.jpg",
    "./assets/project-assets/2022-11-工作室项目-李宁成都太古里开业/04.jpg",
    "./assets/project-assets/2022-11-工作室项目-李宁成都太古里开业/05.jpg",
    "./assets/project-assets/2022-11-工作室项目-李宁成都太古里开业/06.jpg",
    "./assets/project-assets/2022-11-工作室项目-李宁成都太古里开业/07.jpg"
  ],
  "2022-11-工作室项目-中粮控股大悦城15周年庆典": [
    "./assets/project-assets/2022-11-工作室项目-中粮控股大悦城15周年庆典/01.jpg",
    "./assets/project-assets/2022-11-工作室项目-中粮控股大悦城15周年庆典/02.jpg",
    "./assets/project-assets/2022-11-工作室项目-中粮控股大悦城15周年庆典/03.jpg",
    "./assets/project-assets/2022-11-工作室项目-中粮控股大悦城15周年庆典/04.jpg",
    "./assets/project-assets/2022-11-工作室项目-中粮控股大悦城15周年庆典/05.jpg",
    "./assets/project-assets/2022-11-工作室项目-中粮控股大悦城15周年庆典/06.jpg",
    "./assets/project-assets/2022-11-工作室项目-中粮控股大悦城15周年庆典/07.jpg"
  ],
  "2022-11-工作室项目-字节跳动元旦春节装饰": [
    "./assets/project-assets/2022-11-工作室项目-字节跳动元旦春节装饰/01.jpg",
    "./assets/project-assets/2022-11-工作室项目-字节跳动元旦春节装饰/02.jpg",
    "./assets/project-assets/2022-11-工作室项目-字节跳动元旦春节装饰/03.jpg",
    "./assets/project-assets/2022-11-工作室项目-字节跳动元旦春节装饰/04.jpg",
    "./assets/project-assets/2022-11-工作室项目-字节跳动元旦春节装饰/05.jpg",
    "./assets/project-assets/2022-11-工作室项目-字节跳动元旦春节装饰/06.jpg",
    "./assets/project-assets/2022-11-工作室项目-字节跳动元旦春节装饰/07.jpg"
  ],
  "2022-10-工作室项目-百度联盟峰会": [
    "./assets/project-assets/2022-10-工作室项目-百度联盟峰会/01.jpg",
    "./assets/project-assets/2022-10-工作室项目-百度联盟峰会/02.jpg",
    "./assets/project-assets/2022-10-工作室项目-百度联盟峰会/03.jpg",
    "./assets/project-assets/2022-10-工作室项目-百度联盟峰会/04.jpg",
    "./assets/project-assets/2022-10-工作室项目-百度联盟峰会/05.jpg",
    "./assets/project-assets/2022-10-工作室项目-百度联盟峰会/06.jpg",
    "./assets/project-assets/2022-10-工作室项目-百度联盟峰会/07.jpg"
  ],
  "2022-10-工作室项目-传祺车展": [
    "./assets/project-assets/2022-10-工作室项目-传祺车展/01.jpg",
    "./assets/project-assets/2022-10-工作室项目-传祺车展/02.jpg",
    "./assets/project-assets/2022-10-工作室项目-传祺车展/03.jpg",
    "./assets/project-assets/2022-10-工作室项目-传祺车展/04.jpg",
    "./assets/project-assets/2022-10-工作室项目-传祺车展/05.jpg",
    "./assets/project-assets/2022-10-工作室项目-传祺车展/06.jpg",
    "./assets/project-assets/2022-10-工作室项目-传祺车展/07.jpg"
  ],
  "2022-10-工作室项目-网易游戏社会责任促进中心成立": [
    "./assets/project-assets/2022-10-工作室项目-网易游戏社会责任促进中心成立/01.jpg",
    "./assets/project-assets/2022-10-工作室项目-网易游戏社会责任促进中心成立/02.jpg",
    "./assets/project-assets/2022-10-工作室项目-网易游戏社会责任促进中心成立/03.jpg",
    "./assets/project-assets/2022-10-工作室项目-网易游戏社会责任促进中心成立/04.jpg",
    "./assets/project-assets/2022-10-工作室项目-网易游戏社会责任促进中心成立/05.jpg",
    "./assets/project-assets/2022-10-工作室项目-网易游戏社会责任促进中心成立/06.jpg",
    "./assets/project-assets/2022-10-工作室项目-网易游戏社会责任促进中心成立/07.jpg"
  ],
  "2022-10-工作室项目-现代巡展": [
    "./assets/project-assets/2022-10-工作室项目-现代巡展/01.jpg",
    "./assets/project-assets/2022-10-工作室项目-现代巡展/02.jpg",
    "./assets/project-assets/2022-10-工作室项目-现代巡展/03.jpg",
    "./assets/project-assets/2022-10-工作室项目-现代巡展/04.jpg",
    "./assets/project-assets/2022-10-工作室项目-现代巡展/05.jpg",
    "./assets/project-assets/2022-10-工作室项目-现代巡展/06.jpg",
    "./assets/project-assets/2022-10-工作室项目-现代巡展/07.jpg"
  ],
  "2022-09-工作室项目-浑南音乐节运营": [
    "./assets/project-assets/2022-09-工作室项目-浑南音乐节运营/01.jpg",
    "./assets/project-assets/2022-09-工作室项目-浑南音乐节运营/02.jpg",
    "./assets/project-assets/2022-09-工作室项目-浑南音乐节运营/03.jpg",
    "./assets/project-assets/2022-09-工作室项目-浑南音乐节运营/04.jpg",
    "./assets/project-assets/2022-09-工作室项目-浑南音乐节运营/05.jpg",
    "./assets/project-assets/2022-09-工作室项目-浑南音乐节运营/06.jpg"
  ],
  "2022-09-工作室项目-卡游嘉年华": [
    "./assets/project-assets/2022-09-工作室项目-卡游嘉年华/01.jpg",
    "./assets/project-assets/2022-09-工作室项目-卡游嘉年华/02.jpg",
    "./assets/project-assets/2022-09-工作室项目-卡游嘉年华/03.jpg",
    "./assets/project-assets/2022-09-工作室项目-卡游嘉年华/04.jpg",
    "./assets/project-assets/2022-09-工作室项目-卡游嘉年华/05.jpg",
    "./assets/project-assets/2022-09-工作室项目-卡游嘉年华/06.jpg",
    "./assets/project-assets/2022-09-工作室项目-卡游嘉年华/07.jpg"
  ],
  "2022-09-工作室项目-潜江旅游ip企划": [
    "./assets/project-assets/2022-09-工作室项目-潜江旅游ip企划/01.jpg",
    "./assets/project-assets/2022-09-工作室项目-潜江旅游ip企划/02.jpg",
    "./assets/project-assets/2022-09-工作室项目-潜江旅游ip企划/03.jpg",
    "./assets/project-assets/2022-09-工作室项目-潜江旅游ip企划/04.jpg",
    "./assets/project-assets/2022-09-工作室项目-潜江旅游ip企划/05.jpg",
    "./assets/project-assets/2022-09-工作室项目-潜江旅游ip企划/06.jpg",
    "./assets/project-assets/2022-09-工作室项目-潜江旅游ip企划/07.jpg"
  ],
  "2022-09-工作室项目-小米双十一": [
    "./assets/project-assets/2022-09-工作室项目-小米双十一/01.jpg",
    "./assets/project-assets/2022-09-工作室项目-小米双十一/02.jpg",
    "./assets/project-assets/2022-09-工作室项目-小米双十一/03.jpg",
    "./assets/project-assets/2022-09-工作室项目-小米双十一/04.jpg",
    "./assets/project-assets/2022-09-工作室项目-小米双十一/05.jpg",
    "./assets/project-assets/2022-09-工作室项目-小米双十一/06.jpg",
    "./assets/project-assets/2022-09-工作室项目-小米双十一/07.jpg"
  ],
  "2022-09-工作室项目-boeipc大会展台": [
    "./assets/project-assets/2022-09-工作室项目-boeipc大会展台/01.jpg",
    "./assets/project-assets/2022-09-工作室项目-boeipc大会展台/02.jpg",
    "./assets/project-assets/2022-09-工作室项目-boeipc大会展台/03.jpg",
    "./assets/project-assets/2022-09-工作室项目-boeipc大会展台/04.jpg",
    "./assets/project-assets/2022-09-工作室项目-boeipc大会展台/05.jpg",
    "./assets/project-assets/2022-09-工作室项目-boeipc大会展台/06.jpg",
    "./assets/project-assets/2022-09-工作室项目-boeipc大会展台/07.jpg"
  ],
  "2022-08-工作室项目-度小满聚合支付大会": [
    "./assets/project-assets/2022-08-工作室项目-度小满聚合支付大会/01.jpg",
    "./assets/project-assets/2022-08-工作室项目-度小满聚合支付大会/02.jpg",
    "./assets/project-assets/2022-08-工作室项目-度小满聚合支付大会/03.jpg",
    "./assets/project-assets/2022-08-工作室项目-度小满聚合支付大会/04.jpg",
    "./assets/project-assets/2022-08-工作室项目-度小满聚合支付大会/05.jpg",
    "./assets/project-assets/2022-08-工作室项目-度小满聚合支付大会/06.jpg",
    "./assets/project-assets/2022-08-工作室项目-度小满聚合支付大会/07.jpg"
  ],
  "2022-08-工作室项目-居然之家音乐节": [
    "./assets/project-assets/2022-08-工作室项目-居然之家音乐节/01.jpg",
    "./assets/project-assets/2022-08-工作室项目-居然之家音乐节/02.jpg"
  ],
  "2022-08-工作室项目-快手年框": [
    "./assets/project-assets/2022-08-工作室项目-快手年框/01.jpg",
    "./assets/project-assets/2022-08-工作室项目-快手年框/02.jpg",
    "./assets/project-assets/2022-08-工作室项目-快手年框/03.jpg",
    "./assets/project-assets/2022-08-工作室项目-快手年框/04.jpg",
    "./assets/project-assets/2022-08-工作室项目-快手年框/05.jpg",
    "./assets/project-assets/2022-08-工作室项目-快手年框/06.jpg",
    "./assets/project-assets/2022-08-工作室项目-快手年框/07.jpg"
  ],
  "2022-08-工作室项目-天全县美食节": [
    "./assets/project-assets/2022-08-工作室项目-天全县美食节/01.jpg",
    "./assets/project-assets/2022-08-工作室项目-天全县美食节/02.jpg"
  ],
  "2022-07-工作室项目-2022字节中秋节装修": [
    "./assets/project-assets/2022-07-工作室项目-2022字节中秋节装修/01.jpg",
    "./assets/project-assets/2022-07-工作室项目-2022字节中秋节装修/02.jpg",
    "./assets/project-assets/2022-07-工作室项目-2022字节中秋节装修/03.jpg",
    "./assets/project-assets/2022-07-工作室项目-2022字节中秋节装修/04.jpg",
    "./assets/project-assets/2022-07-工作室项目-2022字节中秋节装修/05.jpg",
    "./assets/project-assets/2022-07-工作室项目-2022字节中秋节装修/06.jpg",
    "./assets/project-assets/2022-07-工作室项目-2022字节中秋节装修/07.jpg"
  ],
  "2022-07-工作室项目-哈弗巡展": [
    "./assets/project-assets/2022-07-工作室项目-哈弗巡展/01.jpg",
    "./assets/project-assets/2022-07-工作室项目-哈弗巡展/02.jpg",
    "./assets/project-assets/2022-07-工作室项目-哈弗巡展/03.jpg",
    "./assets/project-assets/2022-07-工作室项目-哈弗巡展/04.jpg",
    "./assets/project-assets/2022-07-工作室项目-哈弗巡展/05.jpg",
    "./assets/project-assets/2022-07-工作室项目-哈弗巡展/06.jpg",
    "./assets/project-assets/2022-07-工作室项目-哈弗巡展/07.jpg"
  ],
  "2022-07-工作室项目-极狐露营": [
    "./assets/project-assets/2022-07-工作室项目-极狐露营/01.jpg",
    "./assets/project-assets/2022-07-工作室项目-极狐露营/02.jpg"
  ],
  "2022-07-工作室项目-汽车之家车展": [
    "./assets/project-assets/2022-07-工作室项目-汽车之家车展/01.jpg",
    "./assets/project-assets/2022-07-工作室项目-汽车之家车展/02.jpg",
    "./assets/project-assets/2022-07-工作室项目-汽车之家车展/03.jpg",
    "./assets/project-assets/2022-07-工作室项目-汽车之家车展/04.jpg",
    "./assets/project-assets/2022-07-工作室项目-汽车之家车展/05.jpg",
    "./assets/project-assets/2022-07-工作室项目-汽车之家车展/06.jpg",
    "./assets/project-assets/2022-07-工作室项目-汽车之家车展/07.jpg"
  ],
  "2022-07-工作室项目-友邦mdrt": [
    "./assets/project-assets/2022-07-工作室项目-友邦mdrt/01.jpg",
    "./assets/project-assets/2022-07-工作室项目-友邦mdrt/02.jpg",
    "./assets/project-assets/2022-07-工作室项目-友邦mdrt/03.jpg",
    "./assets/project-assets/2022-07-工作室项目-友邦mdrt/04.jpg",
    "./assets/project-assets/2022-07-工作室项目-友邦mdrt/05.jpg",
    "./assets/project-assets/2022-07-工作室项目-友邦mdrt/06.jpg",
    "./assets/project-assets/2022-07-工作室项目-友邦mdrt/07.jpg"
  ],
  "2022-06-工作室项目-h3c": [
    "./assets/project-assets/2022-06-工作室项目-h3c/01.jpg",
    "./assets/project-assets/2022-06-工作室项目-h3c/02.jpg",
    "./assets/project-assets/2022-06-工作室项目-h3c/03.jpg",
    "./assets/project-assets/2022-06-工作室项目-h3c/04.jpg",
    "./assets/project-assets/2022-06-工作室项目-h3c/05.jpg",
    "./assets/project-assets/2022-06-工作室项目-h3c/06.jpg",
    "./assets/project-assets/2022-06-工作室项目-h3c/07.jpg"
  ],
  "2022-05-工作室项目-巨量星图嘉年华": [
    "./assets/project-assets/2022-05-工作室项目-巨量星图嘉年华/01.jpg",
    "./assets/project-assets/2022-05-工作室项目-巨量星图嘉年华/02.jpg",
    "./assets/project-assets/2022-05-工作室项目-巨量星图嘉年华/03.jpg",
    "./assets/project-assets/2022-05-工作室项目-巨量星图嘉年华/04.jpg",
    "./assets/project-assets/2022-05-工作室项目-巨量星图嘉年华/05.jpg",
    "./assets/project-assets/2022-05-工作室项目-巨量星图嘉年华/06.jpg",
    "./assets/project-assets/2022-05-工作室项目-巨量星图嘉年华/07.jpg"
  ],
  "2022-05-工作室项目-小红书渠道营销会": [
    "./assets/project-assets/2022-05-工作室项目-小红书渠道营销会/01.jpg",
    "./assets/project-assets/2022-05-工作室项目-小红书渠道营销会/02.jpg",
    "./assets/project-assets/2022-05-工作室项目-小红书渠道营销会/03.jpg",
    "./assets/project-assets/2022-05-工作室项目-小红书渠道营销会/04.jpg",
    "./assets/project-assets/2022-05-工作室项目-小红书渠道营销会/05.jpg",
    "./assets/project-assets/2022-05-工作室项目-小红书渠道营销会/06.jpg",
    "./assets/project-assets/2022-05-工作室项目-小红书渠道营销会/07.jpg"
  ],
  "2022-05-工作室项目-小米暑促": [
    "./assets/project-assets/2022-05-工作室项目-小米暑促/01.jpg",
    "./assets/project-assets/2022-05-工作室项目-小米暑促/02.jpg",
    "./assets/project-assets/2022-05-工作室项目-小米暑促/03.jpg",
    "./assets/project-assets/2022-05-工作室项目-小米暑促/04.jpg",
    "./assets/project-assets/2022-05-工作室项目-小米暑促/05.jpg",
    "./assets/project-assets/2022-05-工作室项目-小米暑促/06.jpg",
    "./assets/project-assets/2022-05-工作室项目-小米暑促/07.jpg"
  ],
  "2022-05-工作室项目-boe技术品牌赋能计划发布会": [
    "./assets/project-assets/2022-05-工作室项目-boe技术品牌赋能计划发布会/01.jpg",
    "./assets/project-assets/2022-05-工作室项目-boe技术品牌赋能计划发布会/02.jpg",
    "./assets/project-assets/2022-05-工作室项目-boe技术品牌赋能计划发布会/03.jpg",
    "./assets/project-assets/2022-05-工作室项目-boe技术品牌赋能计划发布会/04.jpg",
    "./assets/project-assets/2022-05-工作室项目-boe技术品牌赋能计划发布会/05.jpg",
    "./assets/project-assets/2022-05-工作室项目-boe技术品牌赋能计划发布会/06.jpg",
    "./assets/project-assets/2022-05-工作室项目-boe技术品牌赋能计划发布会/07.jpg"
  ],
  "2022-04-工作室项目-比亚迪粉丝跨界": [
    "./assets/project-assets/2022-04-工作室项目-比亚迪粉丝跨界/01.jpg",
    "./assets/project-assets/2022-04-工作室项目-比亚迪粉丝跨界/02.jpg",
    "./assets/project-assets/2022-04-工作室项目-比亚迪粉丝跨界/03.jpg",
    "./assets/project-assets/2022-04-工作室项目-比亚迪粉丝跨界/04.jpg",
    "./assets/project-assets/2022-04-工作室项目-比亚迪粉丝跨界/05.jpg",
    "./assets/project-assets/2022-04-工作室项目-比亚迪粉丝跨界/06.jpg",
    "./assets/project-assets/2022-04-工作室项目-比亚迪粉丝跨界/07.jpg"
  ],
  "2022-04-工作室项目-哈弗56月区域营销": [
    "./assets/project-assets/2022-04-工作室项目-哈弗56月区域营销/01.jpg",
    "./assets/project-assets/2022-04-工作室项目-哈弗56月区域营销/02.jpg",
    "./assets/project-assets/2022-04-工作室项目-哈弗56月区域营销/03.jpg",
    "./assets/project-assets/2022-04-工作室项目-哈弗56月区域营销/04.jpg",
    "./assets/project-assets/2022-04-工作室项目-哈弗56月区域营销/05.jpg",
    "./assets/project-assets/2022-04-工作室项目-哈弗56月区域营销/06.jpg",
    "./assets/project-assets/2022-04-工作室项目-哈弗56月区域营销/07.jpg"
  ],
  "2022-04-工作室项目-哈佛车展": [
    "./assets/project-assets/2022-04-工作室项目-哈佛车展/01.jpg",
    "./assets/project-assets/2022-04-工作室项目-哈佛车展/02.jpg",
    "./assets/project-assets/2022-04-工作室项目-哈佛车展/03.jpg",
    "./assets/project-assets/2022-04-工作室项目-哈佛车展/04.jpg",
    "./assets/project-assets/2022-04-工作室项目-哈佛车展/05.jpg",
    "./assets/project-assets/2022-04-工作室项目-哈佛车展/06.jpg",
    "./assets/project-assets/2022-04-工作室项目-哈佛车展/07.jpg"
  ],
  "2022-04-工作室项目-李宁极限飞盘大赛": [
    "./assets/project-assets/2022-04-工作室项目-李宁极限飞盘大赛/01.jpg",
    "./assets/project-assets/2022-04-工作室项目-李宁极限飞盘大赛/02.jpg",
    "./assets/project-assets/2022-04-工作室项目-李宁极限飞盘大赛/03.jpg",
    "./assets/project-assets/2022-04-工作室项目-李宁极限飞盘大赛/04.jpg",
    "./assets/project-assets/2022-04-工作室项目-李宁极限飞盘大赛/05.jpg",
    "./assets/project-assets/2022-04-工作室项目-李宁极限飞盘大赛/06.jpg",
    "./assets/project-assets/2022-04-工作室项目-李宁极限飞盘大赛/07.jpg"
  ],
  "2022-04-工作室项目-美好目的地": [
    "./assets/project-assets/2022-04-工作室项目-美好目的地/01.jpg",
    "./assets/project-assets/2022-04-工作室项目-美好目的地/02.jpg"
  ],
  "2022-04-工作室项目-realme火影手机发布会": [
    "./assets/project-assets/2022-04-工作室项目-realme火影手机发布会/01.jpg",
    "./assets/project-assets/2022-04-工作室项目-realme火影手机发布会/02.jpg",
    "./assets/project-assets/2022-04-工作室项目-realme火影手机发布会/03.jpg",
    "./assets/project-assets/2022-04-工作室项目-realme火影手机发布会/04.jpg",
    "./assets/project-assets/2022-04-工作室项目-realme火影手机发布会/05.jpg",
    "./assets/project-assets/2022-04-工作室项目-realme火影手机发布会/06.jpg",
    "./assets/project-assets/2022-04-工作室项目-realme火影手机发布会/07.jpg"
  ],
  "2022-03-工作室项目-55购物节": [
    "./assets/project-assets/2022-03-工作室项目-55购物节/01.jpg",
    "./assets/project-assets/2022-03-工作室项目-55购物节/02.jpg",
    "./assets/project-assets/2022-03-工作室项目-55购物节/03.jpg",
    "./assets/project-assets/2022-03-工作室项目-55购物节/04.jpg",
    "./assets/project-assets/2022-03-工作室项目-55购物节/05.jpg",
    "./assets/project-assets/2022-03-工作室项目-55购物节/06.jpg",
    "./assets/project-assets/2022-03-工作室项目-55购物节/07.jpg"
  ],
  "2022-03-工作室项目-厨房小家电健康趋势发布": [
    "./assets/project-assets/2022-03-工作室项目-厨房小家电健康趋势发布/01.jpg",
    "./assets/project-assets/2022-03-工作室项目-厨房小家电健康趋势发布/02.jpg"
  ],
  "2022-03-工作室项目-度小满年框": [
    "./assets/project-assets/2022-03-工作室项目-度小满年框/01.jpg",
    "./assets/project-assets/2022-03-工作室项目-度小满年框/02.jpg",
    "./assets/project-assets/2022-03-工作室项目-度小满年框/03.jpg",
    "./assets/project-assets/2022-03-工作室项目-度小满年框/04.jpg",
    "./assets/project-assets/2022-03-工作室项目-度小满年框/05.jpg",
    "./assets/project-assets/2022-03-工作室项目-度小满年框/06.jpg",
    "./assets/project-assets/2022-03-工作室项目-度小满年框/07.jpg"
  ],
  "2022-03-工作室项目-wavesummit2022春季": [
    "./assets/project-assets/2022-03-工作室项目-wavesummit2022春季/01.jpg",
    "./assets/project-assets/2022-03-工作室项目-wavesummit2022春季/02.jpg",
    "./assets/project-assets/2022-03-工作室项目-wavesummit2022春季/03.jpg",
    "./assets/project-assets/2022-03-工作室项目-wavesummit2022春季/04.jpg",
    "./assets/project-assets/2022-03-工作室项目-wavesummit2022春季/05.jpg",
    "./assets/project-assets/2022-03-工作室项目-wavesummit2022春季/06.jpg",
    "./assets/project-assets/2022-03-工作室项目-wavesummit2022春季/07.jpg"
  ],
  "2022-02-工作室项目-广汽传祺车展方案": [
    "./assets/project-assets/2022-02-工作室项目-广汽传祺车展方案/01.jpg",
    "./assets/project-assets/2022-02-工作室项目-广汽传祺车展方案/02.jpg",
    "./assets/project-assets/2022-02-工作室项目-广汽传祺车展方案/03.jpg",
    "./assets/project-assets/2022-02-工作室项目-广汽传祺车展方案/04.jpg",
    "./assets/project-assets/2022-02-工作室项目-广汽传祺车展方案/05.jpg",
    "./assets/project-assets/2022-02-工作室项目-广汽传祺车展方案/06.jpg",
    "./assets/project-assets/2022-02-工作室项目-广汽传祺车展方案/07.jpg"
  ],
  "2022-02-工作室项目-李宁workshop": [
    "./assets/project-assets/2022-02-工作室项目-李宁workshop/01.jpg",
    "./assets/project-assets/2022-02-工作室项目-李宁workshop/02.jpg",
    "./assets/project-assets/2022-02-工作室项目-李宁workshop/03.jpg",
    "./assets/project-assets/2022-02-工作室项目-李宁workshop/04.jpg",
    "./assets/project-assets/2022-02-工作室项目-李宁workshop/05.jpg",
    "./assets/project-assets/2022-02-工作室项目-李宁workshop/06.jpg",
    "./assets/project-assets/2022-02-工作室项目-李宁workshop/07.jpg"
  ],
  "2022-02-工作室项目-汽车之家车展预热平行宇宙": [
    "./assets/project-assets/2022-02-工作室项目-汽车之家车展预热平行宇宙/01.jpg",
    "./assets/project-assets/2022-02-工作室项目-汽车之家车展预热平行宇宙/02.jpg",
    "./assets/project-assets/2022-02-工作室项目-汽车之家车展预热平行宇宙/03.jpg",
    "./assets/project-assets/2022-02-工作室项目-汽车之家车展预热平行宇宙/04.jpg",
    "./assets/project-assets/2022-02-工作室项目-汽车之家车展预热平行宇宙/05.jpg",
    "./assets/project-assets/2022-02-工作室项目-汽车之家车展预热平行宇宙/06.jpg",
    "./assets/project-assets/2022-02-工作室项目-汽车之家车展预热平行宇宙/07.jpg"
  ],
  "2022-02-工作室项目-中南置地王者荣耀": [
    "./assets/project-assets/2022-02-工作室项目-中南置地王者荣耀/01.jpg",
    "./assets/project-assets/2022-02-工作室项目-中南置地王者荣耀/02.jpg",
    "./assets/project-assets/2022-02-工作室项目-中南置地王者荣耀/03.jpg",
    "./assets/project-assets/2022-02-工作室项目-中南置地王者荣耀/04.jpg",
    "./assets/project-assets/2022-02-工作室项目-中南置地王者荣耀/05.jpg",
    "./assets/project-assets/2022-02-工作室项目-中南置地王者荣耀/06.jpg",
    "./assets/project-assets/2022-02-工作室项目-中南置地王者荣耀/07.jpg"
  ],
  "2022-01-工作室项目-快手营销大事件": [
    "./assets/project-assets/2022-01-工作室项目-快手营销大事件/01.jpg",
    "./assets/project-assets/2022-01-工作室项目-快手营销大事件/02.jpg",
    "./assets/project-assets/2022-01-工作室项目-快手营销大事件/03.jpg",
    "./assets/project-assets/2022-01-工作室项目-快手营销大事件/04.jpg",
    "./assets/project-assets/2022-01-工作室项目-快手营销大事件/05.jpg",
    "./assets/project-assets/2022-01-工作室项目-快手营销大事件/06.jpg",
    "./assets/project-assets/2022-01-工作室项目-快手营销大事件/07.jpg"
  ],
  "2022-01-工作室项目-mastergo": [
    "./assets/project-assets/2022-01-工作室项目-mastergo/01.jpg",
    "./assets/project-assets/2022-01-工作室项目-mastergo/02.jpg",
    "./assets/project-assets/2022-01-工作室项目-mastergo/03.jpg",
    "./assets/project-assets/2022-01-工作室项目-mastergo/04.jpg",
    "./assets/project-assets/2022-01-工作室项目-mastergo/05.jpg",
    "./assets/project-assets/2022-01-工作室项目-mastergo/06.jpg",
    "./assets/project-assets/2022-01-工作室项目-mastergo/07.jpg"
  ],
  "2022-01-工作室项目-myclarins快闪": [
    "./assets/project-assets/2022-01-工作室项目-myclarins快闪/01.jpg",
    "./assets/project-assets/2022-01-工作室项目-myclarins快闪/02.jpg",
    "./assets/project-assets/2022-01-工作室项目-myclarins快闪/03.jpg",
    "./assets/project-assets/2022-01-工作室项目-myclarins快闪/04.jpg",
    "./assets/project-assets/2022-01-工作室项目-myclarins快闪/05.jpg",
    "./assets/project-assets/2022-01-工作室项目-myclarins快闪/06.jpg",
    "./assets/project-assets/2022-01-工作室项目-myclarins快闪/07.jpg"
  ],
  "2021-00-工作室项目-2021wavesummit": [
    "./assets/project-assets/2021-00-工作室项目-2021wavesummit/01.jpg",
    "./assets/project-assets/2021-00-工作室项目-2021wavesummit/02.jpg",
    "./assets/project-assets/2021-00-工作室项目-2021wavesummit/03.jpg",
    "./assets/project-assets/2021-00-工作室项目-2021wavesummit/04.jpg",
    "./assets/project-assets/2021-00-工作室项目-2021wavesummit/05.jpg",
    "./assets/project-assets/2021-00-工作室项目-2021wavesummit/06.jpg",
    "./assets/project-assets/2021-00-工作室项目-2021wavesummit/07.jpg"
  ],
  "2021-00-工作室项目-88邮箱": [
    "./assets/project-assets/2021-00-工作室项目-88邮箱/01.jpg",
    "./assets/project-assets/2021-00-工作室项目-88邮箱/02.jpg",
    "./assets/project-assets/2021-00-工作室项目-88邮箱/03.jpg",
    "./assets/project-assets/2021-00-工作室项目-88邮箱/04.jpg",
    "./assets/project-assets/2021-00-工作室项目-88邮箱/05.jpg",
    "./assets/project-assets/2021-00-工作室项目-88邮箱/06.jpg",
    "./assets/project-assets/2021-00-工作室项目-88邮箱/07.jpg"
  ],
  "2021-00-工作室项目-抖音服务商大会": [
    "./assets/project-assets/2021-00-工作室项目-抖音服务商大会/01.jpg",
    "./assets/project-assets/2021-00-工作室项目-抖音服务商大会/02.jpg",
    "./assets/project-assets/2021-00-工作室项目-抖音服务商大会/03.jpg",
    "./assets/project-assets/2021-00-工作室项目-抖音服务商大会/04.jpg",
    "./assets/project-assets/2021-00-工作室项目-抖音服务商大会/05.jpg",
    "./assets/project-assets/2021-00-工作室项目-抖音服务商大会/06.jpg",
    "./assets/project-assets/2021-00-工作室项目-抖音服务商大会/07.jpg"
  ],
  "2021-00-工作室项目-方舟健客": [
    "./assets/project-assets/2021-00-工作室项目-方舟健客/01.jpg",
    "./assets/project-assets/2021-00-工作室项目-方舟健客/02.jpg",
    "./assets/project-assets/2021-00-工作室项目-方舟健客/03.jpg",
    "./assets/project-assets/2021-00-工作室项目-方舟健客/04.jpg",
    "./assets/project-assets/2021-00-工作室项目-方舟健客/05.jpg",
    "./assets/project-assets/2021-00-工作室项目-方舟健客/06.jpg",
    "./assets/project-assets/2021-00-工作室项目-方舟健客/07.jpg"
  ],
  "2021-00-工作室项目-花房之夜": [
    "./assets/project-assets/2021-00-工作室项目-花房之夜/01.jpg",
    "./assets/project-assets/2021-00-工作室项目-花房之夜/02.jpg",
    "./assets/project-assets/2021-00-工作室项目-花房之夜/03.jpg",
    "./assets/project-assets/2021-00-工作室项目-花房之夜/04.jpg",
    "./assets/project-assets/2021-00-工作室项目-花房之夜/05.jpg",
    "./assets/project-assets/2021-00-工作室项目-花房之夜/06.jpg",
    "./assets/project-assets/2021-00-工作室项目-花房之夜/07.jpg"
  ],
  "2021-00-工作室项目-极氪": [
    "./assets/project-assets/2021-00-工作室项目-极氪/01.jpg",
    "./assets/project-assets/2021-00-工作室项目-极氪/02.jpg",
    "./assets/project-assets/2021-00-工作室项目-极氪/03.jpg",
    "./assets/project-assets/2021-00-工作室项目-极氪/04.jpg",
    "./assets/project-assets/2021-00-工作室项目-极氪/05.jpg",
    "./assets/project-assets/2021-00-工作室项目-极氪/06.jpg",
    "./assets/project-assets/2021-00-工作室项目-极氪/07.jpg"
  ],
  "2021-00-工作室项目-快手红人节": [
    "./assets/project-assets/2021-00-工作室项目-快手红人节/01.jpg",
    "./assets/project-assets/2021-00-工作室项目-快手红人节/02.jpg",
    "./assets/project-assets/2021-00-工作室项目-快手红人节/03.jpg",
    "./assets/project-assets/2021-00-工作室项目-快手红人节/04.jpg",
    "./assets/project-assets/2021-00-工作室项目-快手红人节/05.jpg",
    "./assets/project-assets/2021-00-工作室项目-快手红人节/06.jpg",
    "./assets/project-assets/2021-00-工作室项目-快手红人节/07.jpg"
  ],
  "2021-00-工作室项目-量子之歌": [
    "./assets/project-assets/2021-00-工作室项目-量子之歌/01.jpg",
    "./assets/project-assets/2021-00-工作室项目-量子之歌/02.jpg",
    "./assets/project-assets/2021-00-工作室项目-量子之歌/03.jpg",
    "./assets/project-assets/2021-00-工作室项目-量子之歌/04.jpg",
    "./assets/project-assets/2021-00-工作室项目-量子之歌/05.jpg",
    "./assets/project-assets/2021-00-工作室项目-量子之歌/06.jpg",
    "./assets/project-assets/2021-00-工作室项目-量子之歌/07.jpg"
  ],
  "2021-00-工作室项目-领克": [
    "./assets/project-assets/2021-00-工作室项目-领克/01.jpg",
    "./assets/project-assets/2021-00-工作室项目-领克/02.jpg",
    "./assets/project-assets/2021-00-工作室项目-领克/03.jpg",
    "./assets/project-assets/2021-00-工作室项目-领克/04.jpg",
    "./assets/project-assets/2021-00-工作室项目-领克/05.jpg",
    "./assets/project-assets/2021-00-工作室项目-领克/06.jpg",
    "./assets/project-assets/2021-00-工作室项目-领克/07.jpg"
  ],
  "2021-00-工作室项目-螺狮粉小镇": [
    "./assets/project-assets/2021-00-工作室项目-螺狮粉小镇/01.jpg",
    "./assets/project-assets/2021-00-工作室项目-螺狮粉小镇/02.jpg",
    "./assets/project-assets/2021-00-工作室项目-螺狮粉小镇/03.jpg",
    "./assets/project-assets/2021-00-工作室项目-螺狮粉小镇/04.jpg",
    "./assets/project-assets/2021-00-工作室项目-螺狮粉小镇/05.jpg",
    "./assets/project-assets/2021-00-工作室项目-螺狮粉小镇/06.jpg",
    "./assets/project-assets/2021-00-工作室项目-螺狮粉小镇/07.jpg"
  ],
  "2021-00-工作室项目-汽车之家性能嘉年华": [
    "./assets/project-assets/2021-00-工作室项目-汽车之家性能嘉年华/01.jpg",
    "./assets/project-assets/2021-00-工作室项目-汽车之家性能嘉年华/02.jpg",
    "./assets/project-assets/2021-00-工作室项目-汽车之家性能嘉年华/03.jpg",
    "./assets/project-assets/2021-00-工作室项目-汽车之家性能嘉年华/04.jpg",
    "./assets/project-assets/2021-00-工作室项目-汽车之家性能嘉年华/05.jpg",
    "./assets/project-assets/2021-00-工作室项目-汽车之家性能嘉年华/06.jpg",
    "./assets/project-assets/2021-00-工作室项目-汽车之家性能嘉年华/07.jpg"
  ],
  "2021-00-工作室项目-小米年终系列活动": [
    "./assets/project-assets/2021-00-工作室项目-小米年终系列活动/01.jpg",
    "./assets/project-assets/2021-00-工作室项目-小米年终系列活动/02.jpg",
    "./assets/project-assets/2021-00-工作室项目-小米年终系列活动/03.jpg",
    "./assets/project-assets/2021-00-工作室项目-小米年终系列活动/04.jpg",
    "./assets/project-assets/2021-00-工作室项目-小米年终系列活动/05.jpg",
    "./assets/project-assets/2021-00-工作室项目-小米年终系列活动/06.jpg",
    "./assets/project-assets/2021-00-工作室项目-小米年终系列活动/07.jpg"
  ]
};
