"""把「技术思考」系列文章导出为网站数据。

读取 个人网站/技术思考/0X-*.md：
- 解析 frontmatter（title / order）
- ![[图片]] 从库根「附件」目录复制压缩到 assets/writing/，正文替换为本地引用
- [[wikilink]] 转为纯文本
- markdown-it-py 转 HTML
- 索引文件的「—— 一句话」作为文章副标题
输出 writing-data.js（window.writingArticles）。改稿后重跑一次即可。
"""

import json
import re
import shutil
from pathlib import Path

from markdown_it import MarkdownIt
from PIL import Image

ROOT = Path("/Users/sunrui/Documents/Obsidian Vault")
SITE = ROOT / "个人网站"
SRC = SITE / "技术思考"
ATTACH = ROOT / "附件"
OUT = SITE / "assets" / "writing"
OUT.mkdir(parents=True, exist_ok=True)

md = MarkdownIt("commonmark", {"html": True, "breaks": False}).enable("table")

# 索引里的副标题：1. [[01 AI实操指南——工作流]] —— 把 AI 从聊天玩具变成工作流的一环
subs = {}
index_text = (SRC / "技术思考.md").read_text(encoding="utf-8")
for m in re.finditer(r"\d+\.\s*\[\[([^\]|]+)\]\]\s*——\s*([^\n]+)", index_text):
    subs[m.group(1).strip()] = m.group(2).strip()


def parse_frontmatter(text):
    if not text.startswith("---"):
        return {}, text
    end = text.index("\n---", 3)
    meta = {}
    for line in text[3:end].strip().split("\n"):
        m = re.match(r"^([A-Za-z0-9_-]+):\s*(.*)$", line)
        if m:
            meta[m.group(1)] = m.group(2).strip().strip("\"'")
    return meta, text[end + 4:].lstrip("\n")


def export_image(name, key, idx):
    src = ATTACH / name
    if not src.is_file():
        return None
    ext = src.suffix.lower().lstrip(".") or "png"
    dst = OUT / f"{key}-{idx:02d}.{ext}"
    if not dst.exists():
        try:
            img = Image.open(src).convert("RGB")
            if img.width > 1400:
                img = img.resize((1400, round(img.height * 1400 / img.width)), Image.LANCZOS)
            if ext in ("jpg", "jpeg"):
                img.save(dst, "JPEG", quality=80)
            else:
                dst = dst.with_suffix(".jpg")
                img.save(dst, "JPEG", quality=80)
        except Exception:
            shutil.copyfile(src, dst)
    return f"./assets/writing/{dst.name}"


articles = []
files = sorted(p for p in SRC.glob("0*.md"))
for path in files:
    meta, body = parse_frontmatter(path.read_text(encoding="utf-8"))
    order = int(meta.get("order") or path.name[:2])
    key = f"{order:02d}"
    title = meta.get("title") or path.stem

    idx = 0

    def repl_image(match):
        nonlocal_idx[0] += 1
        local = export_image(match.group(1).split("|")[0].strip(), key, nonlocal_idx[0])
        return f"![{title}]({local})" if local else ""

    nonlocal_idx = [0]
    body = re.sub(r"!\[\[([^\]]+)\]\]", repl_image, body)
    body = re.sub(r"\[\[([^\]|]+)\|?([^\]]*)\]\]", lambda m: m.group(2) or m.group(1), body)

    html = md.render(body)
    # 第一张大标题（文章文件名已表达），保留内容即可
    articles.append({
        "slug": key,
        "order": order,
        "title": title,
        "sub": subs.get(path.stem, ""),
        "html": html,
    })

out = "// Auto-generated by scripts/export_writing.py. Rerun after editing 技术思考/*.md.\n"
out += "window.writingArticles = " + json.dumps(articles, ensure_ascii=False, indent=2) + ";\n"
(SITE / "writing-data.js").write_text(out, encoding="utf-8")
print(f"导出 {len(articles)} 篇文章，图片 {len(list(OUT.glob('*')))} 张")
