"""从 DayOne 缩略图里选照片做拍立得日记墙。

筛选规则：文件大于 40KB（信息量代理），按修改时间排序后均匀抽 30 张，
复制到 assets/life/dayone/，并生成 src/dayone-photos.js。
要换照片：删掉 assets/life/dayone/ 里不想要的，把备选原名改编号放进去，
或调 COUNT 重跑。
"""

import json
import shutil
from pathlib import Path

ROOT = Path("/Users/sunrui/Documents/Obsidian Vault")
SITE = ROOT / "个人网站"
SRC = ROOT / "附件" / "DayOne" / "thumbs"
OUT = SITE / "assets" / "life" / "dayone"
OUT.mkdir(parents=True, exist_ok=True)

COUNT = 30
MIN_BYTES = 40_000

candidates = sorted(
    (p for p in SRC.glob("*.jpg") if p.stat().st_size >= MIN_BYTES),
    key=lambda p: p.stat().st_mtime,
)
print(f"候选: {len(candidates)}")

step = max(1, len(candidates) // COUNT)
picked = candidates[::step][:COUNT]

for old in OUT.glob("*.jpg"):
    old.unlink()
names = []
for i, p in enumerate(picked, 1):
    name = f"dayone-{i:02d}.jpg"
    shutil.copyfile(p, OUT / name)
    names.append(name)

out_js = "// Auto-generated by scripts/export_dayone.py.\n"
out_js += "export const dayonePhotos = " + json.dumps(
    [f"/assets/life/dayone/{n}" for n in names], ensure_ascii=False, indent=2
) + ";\n"
(SITE / "src" / "dayone-photos.js").write_text(out_js, encoding="utf-8")
print(f"选出 {len(names)} 张 -> assets/life/dayone/")
