"""把 project-index.js 里工作室项目的 hero/images（Obsidian 相对路径）本地化。

逐条读取 slug 含「工作室项目」的条目，把 hero + images 引用的图片
压缩为宽<=1600 的 JPEG，存到 assets/project-assets/<slug>/<序号>.jpg，
并输出 project-gallery.js（window.projectGallery 映射）供 case.js 详情页使用。
已转换过的同名文件跳过（增量）。project-index.js 重新生成后再跑一次即可。
"""

import json
import re
from pathlib import Path

from PIL import Image

ROOT = Path("/Users/sunrui/Documents/Obsidian Vault")
SITE = ROOT / "个人网站"
OUT = SITE / "assets" / "project-assets"
OUT.mkdir(parents=True, exist_ok=True)

src = (SITE / "project-index.js").read_text(encoding="utf-8")
data = json.loads(re.search(r"window\.fullProjectIndex = (\[.*\]);\s*$", src, re.S).group(1))

gallery = {}
converted = skipped = missing = 0
for p in data:
    slug = p.get("slug", "")
    if "工作室项目" not in slug:
        continue
    paths = [p.get("hero") or "", *(p.get("images") or [])]
    local = []
    slot = OUT / slug
    for i, rel in enumerate(paths):
        if not rel or rel.lower().endswith(".svg"):
            continue
        src_file = (SITE / rel).resolve()
        if not src_file.is_file():
            missing += 1
            continue
        dst = slot / f"{i:02d}.jpg"
        if not dst.exists():
            slot.mkdir(parents=True, exist_ok=True)
            try:
                img = Image.open(src_file).convert("RGB")
                if img.width > 1600:
                    img = img.resize((1600, round(img.height * 1600 / img.width)), Image.LANCZOS)
                img.save(dst, "JPEG", quality=78)
                converted += 1
            except Exception:
                missing += 1
                continue
        else:
            skipped += 1
        local.append(f"./assets/project-assets/{slug}/{i:02d}.jpg")
    if local:
        gallery[slug] = local

out_js = "// Auto-generated by scripts/localize_project_images.py. Rerun after project-index.js refreshes.\n"
out_js += "window.projectGallery = " + json.dumps(gallery, ensure_ascii=False, indent=2) + ";\n"
(SITE / "project-gallery.js").write_text(out_js, encoding="utf-8")
print(f"条目: {len(gallery)}, 新转: {converted}, 跳过: {skipped}, 缺源: {missing}")
