// 案例库共享数据：主页画布与独立文件夹页面（folder.html）共同使用。

export const caseHref = (slug) => `case.html?project=${encodeURIComponent(slug)}`;

export const prPlanningProjects = [
  {
    title: "一汽丰田",
    label: "品牌发布 / 新品发布会",
    year: "2025-12",
    image: "/assets/project-covers/2025-12-工作室项目-一汽丰田.png",
    text: "公关策划",
    href: caseHref("2025-12-工作室项目-一汽丰田"),
  },
  {
    title: "岚图技术品牌年度公关",
    label: "品牌年度 / 整合营销",
    year: "2025-12",
    image: "/assets/project-covers/2025-12-工作室项目-岚图技术品牌年度公关.png",
    text: "公关策划",
    href: caseHref("2025-12-工作室项目-岚图技术品牌年度公关"),
  },
  {
    title: "风云T9深度自驾公益体验之旅",
    label: "消费者体验 / 路演 / 快闪",
    year: "2025-09",
    image: "/assets/project-covers/2025-09-工作室项目-风云t9深度自驾公益体验之旅.png",
    text: "公关策划",
    href: caseHref("2025-09-工作室项目-风云t9深度自驾公益体验之旅"),
  },
  {
    title: "iCAR品牌年度",
    label: "品牌年度 / 整合营销",
    year: "2024-11",
    image: "/assets/project-covers/2024-11-工作室项目-icar品牌年度.png",
    text: "公关策划",
    href: caseHref("2024-11-工作室项目-icar品牌年度"),
  },
  {
    title: "腾讯 OPENDAY",
    label: "公益 / 社会议题项目",
    year: "2024-08",
    image: "/assets/project-covers/2024-08-工作室项目-腾讯openday.png",
    text: "公关策划",
    href: caseHref("2024-08-工作室项目-腾讯openday"),
  },
  {
    title: "网易游戏社会责任促进中心成立",
    label: "文旅 / 城市 / 商业空间企划",
    year: "2022-10",
    image: "/assets/project-covers/2022-10-工作室项目-网易游戏社会责任促进中心成立.png",
    text: "公关策划",
    href: caseHref("2022-10-工作室项目-网易游戏社会责任促进中心成立"),
  },
  {
    title: "极狐露营",
    label: "消费者体验 / 路演 / 快闪",
    year: "2022-07",
    image: "/assets/project-covers/2022-07-工作室项目-极狐露营.png",
    text: "公关策划",
    href: caseHref("2022-07-工作室项目-极狐露营"),
  },
  {
    title: "小米暑促",
    label: "消费者体验 / 路演 / 快闪",
    year: "2022-05",
    image: "/assets/project-covers/2022-05-工作室项目-小米暑促.png",
    text: "公关策划",
    href: caseHref("2022-05-工作室项目-小米暑促"),
  },
  {
    title: "比亚迪粉丝跨界",
    label: "消费者体验 / 路演 / 快闪",
    year: "2022-04",
    image: "/assets/project-covers/2022-04-工作室项目-比亚迪粉丝跨界.png",
    text: "公关策划",
    href: caseHref("2022-04-工作室项目-比亚迪粉丝跨界"),
  },
  {
    title: "哈弗5-6月区域营销",
    label: "消费者体验 / 路演 / 快闪",
    year: "2022-04",
    image: "/assets/project-covers/2022-04-工作室项目-哈弗56月区域营销.png",
    text: "公关策划",
    href: caseHref("2022-04-工作室项目-哈弗56月区域营销"),
  },
  {
    title: "美好目的地",
    label: "文旅 / 城市 / 商业空间企划",
    year: "2022-04",
    image: "/assets/project-covers/2022-04-工作室项目-美好目的地.png",
    text: "公关策划",
    href: caseHref("2022-04-工作室项目-美好目的地"),
  },
  {
    title: "厨房小家电健康趋势发布",
    label: "展览展示 / 展台 / 车展",
    year: "2022-03",
    image: "/assets/project-covers/2022-03-工作室项目-厨房小家电健康趋势发布.png",
    text: "公关策划",
    href: caseHref("2022-03-工作室项目-厨房小家电健康趋势发布"),
  },
  {
    title: "快手营销大事件",
    label: "展览展示 / 展台 / 车展",
    year: "2022-01",
    image: "/assets/project-covers/2022-01-工作室项目-快手营销大事件.png",
    text: "公关策划",
    href: caseHref("2022-01-工作室项目-快手营销大事件"),
  },
];

export const experienceProjects = [
  {
    title: "TCL 链博会",
    label: "供应链博览会 / AI 展台",
    year: "2026-04",
    image: "/assets/cases/tcl/hero.png",
    text: "把多产品、多部门的 AI 能力组织成一个可理解、可参观、可汇报的产业展台。",
    href: caseHref("2026-04-工作室项目-tcl链博会"),
  },
  {
    title: "ROG BW",
    label: "游戏展区 / 玩家任务系统",
    year: "2026-04",
    image: "/assets/cases/rog-bw/hero.png",
    text: "用本命之地、任务清单和互动闭环，把展区写成一个有规则的玩家行动空间。",
    href: caseHref("2026-04-工作室项目-rogbw"),
  },
  {
    title: "TROUVER 俄罗斯发布会",
    label: "海外发布 / 渠道体验",
    year: "2026-04",
    image: "/assets/cases/trouver/hero.png",
    text: "面对全新市场和高认知壁垒，用可验证的体验路径建立技术产品的首次公共理解。",
    href: caseHref("2026-04-工作室项目-trouver"),
  },
  {
    title: "中电展位方案",
    label: "央企展厅 / 总部级表达",
    year: "2026-04",
    image: "/assets/cases/cetc/hero.png",
    text: "把总部级表达、产业成果、裸眼 3D 和动线秩序组织成一个可进入的展厅世界观。",
    href: caseHref("2026-04-工作室项目-中电展位方案"),
  },
  {
    title: "iCAR A展运营",
    label: "汽车 A 展 / 展台运营",
    year: "2026-03",
    image: "/assets/cases/icar-a/hero.png",
    text: "让年轻汽车品牌在高密度展会里被记住，用体验、打卡和传播路径连接产品性格。",
    href: caseHref("2026-03-工作室项目-icara展运营"),
  },
  {
    title: "威麟汽车发布会",
    label: "发布会 / 试驾体验",
    year: "2026-02",
    image: "/assets/cases/weylin/hero.png",
    text: "把产品卖点放回具体生活，用路线、试驾科目和停留区完成场景化体验验证。",
    href: caseHref("2026-02-工作室项目-威麟汽车发布会"),
  },
  {
    title: "YONEX 嘉年华",
    label: "体育嘉年华 / 球迷体验",
    year: "2026-01",
    image: "/assets/cases/yonex/hero.png",
    text: "把羽毛球品牌做成球迷可以下场参与、愿意停留和分享的嘉年华现场。",
    href: caseHref("2026-01-工作室项目-yonex嘉年华资料"),
  },
  {
    title: "字节跳动办公空间",
    label: "办公空间 / 空间改造",
    year: "2025-11",
    image: "/assets/project-covers/2025-11-工作室项目-字节装修.png",
    text: "办公空间改造方案，让空间设计服务于团队文化与日常工作效率。",
    href: caseHref("2025-11-工作室项目-字节装修"),
  },
  {
    title: "江淮车展",
    label: "车展展台 / 品牌展陈",
    year: "2025-07",
    image: "/assets/project-covers/2025-07-工作室项目-江淮.png",
    text: "成都、广州车展展台，老牌车企新能源转型的现场表达。",
    href: caseHref("2025-07-工作室项目-江淮"),
  },
  {
    title: "一汽丰田 A展",
    label: "汽车 A 展 / 展台运营",
    year: "2025-05",
    image: "/assets/project-covers/2025-05-工作室项目-一汽丰田a展.png",
    text: "A 展展台运营：产品展示、集客互动与现场转化的完整组织。",
    href: caseHref("2025-05-工作室项目-一汽丰田a展"),
  },
  {
    title: "抖音直播嘉年华游园会",
    label: "平台嘉年华 / 游园互动",
    year: "2024-12",
    image: "/assets/project-covers/2024-12-工作室项目-抖音直播嘉年华游园会.png",
    text: "把直播生态装进游园会，用场景化和娱乐化组织平台活动体验。",
    href: caseHref("2024-12-工作室项目-抖音直播嘉年华游园会"),
  },
  {
    title: "零跑 A展",
    label: "汽车 A 展 / 展台展陈",
    year: "2024-12",
    image: "/assets/project-covers/2024-12-工作室项目-零跑a展.png",
    text: "零跑 A 级车展展台方案与现场运营。",
    href: caseHref("2024-12-工作室项目-零跑a展"),
  },
  {
    title: "比亚迪智能化战略发布会",
    label: "集团战略发布 / 科技事件",
    year: "2024-12",
    image: "/assets/project-covers/2024-12-工作室项目-比亚迪智能化战略发布会.png",
    text: "把天神之眼、全民智驾时代和 D-SPACE 超级社区，从技术名词转译成可感知的体验与传播结构。",
    href: caseHref("2024-12-工作室项目-比亚迪智能化战略发布会"),
  },
  {
    title: "埃安泰国车展",
    label: "海外车展 / 品牌展陈",
    year: "2024-10",
    image: "/assets/project-covers/2024-10-工作室项目-埃安泰国车展.png",
    text: "品牌出海语境下的展台体验与产品传播，连续两年沉淀。",
    href: caseHref("2024-10-工作室项目-埃安泰国车展"),
  },
  {
    title: "小鹏发布会",
    label: "智驾发布 / 展区互动体验",
    year: "2024-07",
    image: "/assets/project-covers/2024-07-工作室项目-小鹏发布会.png",
    text: "围绕 AI 天玑系统与 XNGP 设计互动展区和打卡路径，让智驾能力在现场被亲手验证。",
    href: caseHref("2024-07-工作室项目-小鹏发布会"),
  },
  {
    title: "联想联通合作伙伴大会展台",
    label: "合作伙伴大会 / 科技展台",
    year: "2024-07",
    image: "/assets/project-covers/2024-07-工作室项目-联想联通合作伙伴大会展台.png",
    text: "从展台设计、内容贴图到执行落地的完整交付。",
    href: caseHref("2024-07-工作室项目-联想联通合作伙伴大会展台"),
  },
  {
    title: "奇瑞 A展运营",
    label: "汽车 A 展 / 展台运营",
    year: "2024-03",
    image: "/assets/project-covers/2024-03-工作室项目-奇瑞a展运营.png",
    text: "奇瑞 A 展运营：展台内容、互动机制与现场执行。",
    href: caseHref("2024-03-工作室项目-奇瑞a展运营"),
  },
  {
    title: "京东供应链金融科技大会",
    label: "行业大会 / 展陈体验",
    year: "2023-09",
    image: "/assets/project-covers/2023-09-工作室项目-京东供应链金融科技大会.png",
    text: "供应链金融议题的展陈化表达与大会体验设计。",
    href: caseHref("2023-09-工作室项目-京东供应链金融科技大会"),
  },
  {
    title: "广汽传祺广州车展",
    label: "A级车展 / 展台展陈",
    year: "2023-09",
    image: "/assets/project-covers/2023-09-工作室项目-广汽传祺广州车展.png",
    text: "广州车展展台方案：主题概念、空间布局与现场内容的整体组织。",
    href: caseHref("2023-09-工作室项目-广汽传祺广州车展"),
  },
  {
    title: "小米 ChinaJoy",
    label: "游戏展会 / 展区体验",
    year: "2023-06",
    image: "/assets/project-covers/2023-06-工作室项目-小米cj.png",
    text: "ChinaJoy 展区：产品体验、玩家互动与现场传播的组织。",
    href: caseHref("2023-06-工作室项目-小米cj"),
  },
];

export const projectFolders = [
  {
    id: "pr",
    title: "品牌公关",
    label: "PR Proposals",
    note: "品牌发布、年度传播、公益体验、区域营销与议题项目。",
    image: "/assets/project-folders/pr.png",
    items: prPlanningProjects,
  },
  {
    id: "experience",
    title: "空间与体验",
    label: "Event Experience",
    note: "活动方案、展区展厅、发布会现场与用户体验路径。",
    image: "/assets/project-folders/experience.png",
    items: experienceProjects,
  },
  {
    id: "ai",
    title: "技术思考",
    label: "AI Practice",
    note: "AI 思考、工具实践、提示词方法与创意工作流实验。",
    image: "/assets/project-folders/ai.png",
    items: [],
  },
  {
    id: "notes",
    title: "创作笔记",
    label: "Creative Notes",
    note: "个人写作、观察、创作草稿与尚未公开的思考入口。",
    image: "/assets/project-folders/notes.png",
    items: [],
  },
];

export const projectTimeValue = (project) => {
  const raw = String(project.year ?? "");
  const match = raw.match(/(\d{4})(?:[-./年](\d{1,2}))?(?:[-./月](\d{1,2}))?/);
  if (!match) return 0;
  const year = Number(match[1]);
  const month = match[2] ? Number(match[2]) : 12;
  const day = match[3] ? Number(match[3]) : 31;
  return new Date(year, month - 1, day).getTime();
};

export const sortProjectsByRecent = (items) =>
  [...items].sort((a, b) => projectTimeValue(b) - projectTimeValue(a));
